#!/bin/sh
# Fab OS: for English sessions, put the Fab-branded English catalogs (en@fabos, generated by
# /usr/lib/fabos/rebrand-catalogs) first; anything they do not cover falls through to the normal English strings.
# Other languages are left exactly as the user configured them.
_fabos_lang="${LANGUAGE:-${LC_ALL:-${LC_MESSAGES:-${LANG:-}}}}"
case "$_fabos_lang" in
  en@fabos*) ;;
  en*|C|C.*|POSIX|"") export LANGUAGE="en@fabos:${LANGUAGE:-en_US}" ;;
esac
unset _fabos_lang
