#!/usr/bin/env bash
# Static checks on the built image: identity, no Canonical branding packages, no snap, legal files present.
set -uo pipefail; PROFILE=${1:-vm}; TAG=fabos:$PROFILE; fail=0
chk() { if eval "$2"; then echo "PASS  $1"; else echo "FAIL  $1"; fail=1; fi; }
R() { podman run --rm "$TAG" bash -c "$1"; }
chk "all fabos packages fully installed"   "! R 'dpkg -l fabos-* | grep -v ^ii | grep -E \"^(i|h|r|u)\"' | grep -q ."
chk "os-release ID=fabos"               "R 'grep -q ^ID=fabos /usr/lib/os-release && grep -q ID_LIKE=.ubuntu /usr/lib/os-release'"
chk "os-release keeps UBUNTU_CODENAME"    "R 'grep -q ^UBUNTU_CODENAME=resolute /usr/lib/os-release'"
chk "lsb_release says FabOS"             "R 'lsb_release -ds' | grep -q 'Fab OS'"
chk "/etc/os-release is a symlink"        "R 'test -L /etc/os-release'"
chk "Ubuntu identity diverted, not lost"  "R 'test -f /usr/lib/os-release.ubuntu && grep -q ^ID=ubuntu /usr/lib/os-release.ubuntu'"
chk "no Canonical artwork packages"       "! R 'dpkg -l ubuntu-wallpapers* plymouth-theme-ubuntu* ubuntu-artwork 2>/dev/null | grep ^ii'"
chk "snapd absent"                        "! R 'dpkg -s snapd 2>/dev/null' >/dev/null"
chk "ubuntu-pro-client absent"            "! R 'dpkg -s ubuntu-pro-client 2>/dev/null' >/dev/null"
chk "plymouth default theme = fabos"     "R 'readlink -f /usr/share/plymouth/themes/default.plymouth' | grep -q themes/fabos/fabos.plymouth"
chk "plymouth script plugin present"      "R 'ls /usr/lib/x86_64-linux-gnu/plymouth/script.so'"
chk "initramfs contains fabos theme"     "R 'lsinitramfs /boot/initrd.img-* | grep -q themes/fabos/fabos.script'"
chk "Inter font installed"                "R 'fc-list | grep -qi Inter-Regular'"
chk "SDDM theme configured"               "R 'grep -q Current=fabos /etc/sddm.conf.d/zz-fabos.conf && test -f /usr/share/sddm/themes/fabos/Main.qml'"
chk "look-and-feel package present"       "R 'test -f /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/defaults'"
chk "wallpaper installed"                 "R 'test -f /usr/share/wallpapers/FabOS/contents/images/1920x1080.png'"
# High-definition assets (2026-09-13): 7 wallpaper sizes light+dark, 4K greeter/splash background, 256 px boot frames,
# bare transparent mark (vector + PNG up to 512 in hicolor, 1024 in pixmaps), scalable/ listed first in the icon theme.
PNGDIM='od -An -tu4 --endian=big -j16 -N8'   # PNG IHDR width/height -> "  W  H" (no python quoting through eval)
chk "wallpapers: 7 sizes, light + dark"     "[ \$(R 'ls /usr/share/wallpapers/FabOS/contents/images/*.png /usr/share/wallpapers/FabOS/contents/images_dark/*.png | wc -l') -eq 14 ]"
chk "wallpaper 4K + 1366x768 present"       "R 'test -f /usr/share/wallpapers/FabOS/contents/images/3840x2160.png && test -f /usr/share/wallpapers/FabOS/contents/images_dark/3840x2160.png && test -f /usr/share/wallpapers/FabOS/contents/images/1366x768.png'"
chk "wallpaper package metadata Fab OS"     "R 'grep -q \"\\\"Name\\\": \\\"Fab OS\\\"\" /usr/share/wallpapers/FabOS/metadata.json && grep -q Apache-2.0 /usr/share/wallpapers/FabOS/metadata.json'"
chk "SDDM background is 3840x2160"          "R \"$PNGDIM /usr/share/sddm/themes/fabos/background.png\" | tr -s ' ' x | grep -q x3840x2160"
chk "SDDM + KSplash use the vector mark"    "R 'test -f /usr/share/sddm/themes/fabos/mark.svg && test -f /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/splash/images/mark.svg'"
chk "lock screen crops, never stretches"    "R 'grep -q ^FillMode=2 /etc/xdg/kscreenlockerrc'"
chk "plymouth frames are 256 px"            "R \"$PNGDIM /usr/share/plymouth/themes/fabos/spinner-00.png\" | tr -s ' ' x | grep -q x256x256"
chk "plymouth script scales to the screen"  "R 'grep -q \"Window.GetHeight()\" /usr/share/plymouth/themes/fabos/fabos.script && grep -q \"Scale(logo_h\" /usr/share/plymouth/themes/fabos/fabos.script'"
chk "hicolor fabos: svg + 512 png"          "R 'test -f /usr/share/icons/hicolor/scalable/apps/fabos.svg && test -f /usr/share/icons/hicolor/scalable/apps/fabos-symbolic.svg && test -f /usr/share/icons/hicolor/512x512/apps/fabos.png'"
chk "hicolor fabos.svg has no tile"         "! R 'grep -q \"<rect width=\\\"64\\\"\" /usr/share/icons/hicolor/scalable/apps/fabos.svg'"
chk "pixmaps fabos.png is 1024 px"          "R \"$PNGDIM /usr/share/pixmaps/fabos.png\" | tr -s ' ' x | grep -q x1024x1024"
chk "default avatar = fabos-face.png"       "R 'readlink /usr/share/sddm/faces/.face.icon' | grep -q fabos-face.png"
chk "FabOS icon theme: fabos + symbolic"    "R 'test -f /usr/share/icons/FabOS/scalable/apps/fabos.svg && test -f /usr/share/icons/FabOS/scalable/apps/fabos-symbolic.svg && test -f /usr/share/icons/FabOS/512x512/apps/fabos.png'"
chk "FabOS index.theme: scalable first, follows scheme" "R 'grep -qE \"^Directories=scalable/status,.*scalable/apps,16x16/apps\" /usr/share/icons/FabOS/index.theme && grep -q ^FollowsColorScheme=true /usr/share/icons/FabOS/index.theme'"
chk "3D logo shipped"                     "R 'test -s /usr/share/fabos/3d/fabos-mark.glb'"
chk "aios runs"                           "R 'aios settings list' >/dev/null 2>&1"
chk "llama-cli present"                   "R 'test -x /usr/bin/llama-cli'"
chk "copyright files retained (>300)"     "[ \$(R 'find /usr/share/doc -name copyright | wc -l') -gt 300 ]"
chk "source offer shipped on system"      "R 'test -f /usr/share/doc/fabos-branding/SOURCE-OFFER'"
chk "kernel + initrd present"             "R 'ls /boot/vmlinuz-* /boot/initrd.img-*'"
chk "sddm enabled"                        "R 'systemctl is-enabled sddm' | grep -q enabled"
chk "FabOS Plasma theme installed"        "R 'test -f /usr/share/plasma/desktoptheme/FabOS/metadata.json && test -f /usr/share/plasma/desktoptheme/FabOS/dialogs/background.svg'"
chk "FabOS icon theme has Settings icons"  "R 'test -e /usr/share/icons/FabOS/48x48/apps/preferences-system-network.png'"
chk "Fab OS session entry (no Plasma name)" "R 'grep -q ^Name=Fab\ OS /usr/local/share/wayland-sessions/fabos.desktop && grep -q SessionDir=/usr/local/share/wayland-sessions /etc/sddm.conf.d/zz-fabos.conf'"
chk "wallet KCM says Fab Wallet (binary)"   "R 'grep -c \"Fab Wallet\" /usr/lib/x86_64-linux-gnu/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwallet5.so' | grep -qv ^0"
chk "Fab Wallet override present"          "R 'grep -q ^Name=Fab\ Wallet /usr/local/share/applications/org.kde.kwalletmanager.desktop'"
chk "no visible KDE names in launcher"     "! R 'grep -lE \"^Name=.*KDE\" /usr/share/applications/*.desktop | while read f; do b=\$(basename \$f); test -f /usr/local/share/applications/\$b || echo \$b; done' | grep -q ."
chk "updates app + polkit + timer"         "R 'test -x /usr/bin/fabos-updates && test -f /usr/share/polkit-1/actions/in.patienceai.fabos.updates.policy && systemctl is-enabled fabos-update-check.timer' | grep -q enabled"
chk "unattended-upgrades allows Fab OS"    "R 'grep -q \"Patience AI:loom\" /etc/apt/apt.conf.d/52fabos-unattended'"
chk "KRunner agent plugin registered"      "R 'test -f /usr/share/krunner/dbusplugins/fabos-runner.desktop && test -f /usr/share/dbus-1/services/in.patienceai.fabos.runner.service'"
chk "file-manager Ask Fab OS action"       "R 'test -f /usr/share/kio/servicemenus/fabos-ask.desktop'"
chk "firefox from Mozilla (not snap shim)"  "R 'dpkg -s firefox' | grep -q 'Maintainer: Mozilla'"
chk "first-boot provisioning shipped"      "R 'test -x /usr/lib/fabos/firstboot.sh && systemctl is-enabled fabos-firstboot.service 2>/dev/null | grep -qE \"enabled|masked\"'"
chk "en@fabos catalogs generated"          "R 'test -s /usr/local/share/locale/en@fabos/LC_MESSAGES/konsole.mo && test -s /usr/local/share/locale/en@fabos/LC_MESSAGES/dolphin.mo'"
chk "session prefers en@fabos"              "R 'test -f /etc/xdg/plasma-workspace/env/50-fabos-language.sh'"
chk "ki18n renames Kate -> Fab Editor"       "R 'HOME=/tmp LANGUAGE=en@fabos:en_US QT_QPA_PLATFORM=offscreen kate --help 2>/dev/null' | grep -q 'Fab Editor - Advanced Text Editor'"
chk "Discover binary never byte-patched"     "R 'test ! -f /usr/bin/plasma-discover.fabos-orig'"
chk "Konsole binaries never byte-patched"      "R 'test ! -f /usr/bin/konsole.fabos-orig && test ! -f /usr/lib/x86_64-linux-gnu/libkonsoleprivate.so.25.12.3.fabos-orig'"
chk "mime override + hidden Software Sources"  "R 'test -f /usr/share/mime/packages/Override.xml && grep -q Hidden=true /usr/local/share/applications/software-properties-qt.desktop'"
chk "light + dark Fab look-and-feel"        "R 'test -f /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/contents/defaults && grep -q DefaultLightLookAndFeel=in.patienceai.fabos.light.desktop /etc/xdg/kdeglobals'"
chk "KDE donation nag off"                  "R 'grep -q autoload=false /etc/xdg/kded6rc'"
chk "no ubuntu account"                     "! R 'grep -q ^ubuntu: /etc/passwd'"
chk "no unminimize MOTD"                    "R 'test ! -f /etc/update-motd.d/60-unminimize'"
chk "Desktop Actions keep their own names"   "! R 'awk \"/^\\[Desktop Action/{a=1} a && /^Name=Fab Terminal/{print}\" /usr/local/share/applications/org.kde.konsole.desktop' | grep -q ."
chk "shortcut component names overridden"    "R 'grep -q ^Name=Fab\ Terminal /usr/local/share/kglobalaccel/org.kde.konsole.desktop'"
chk "Ubuntu web shortcut hidden"            "R 'grep -q Hidden=true /usr/local/share/kf6/searchproviders/ubuntu.desktop'"
chk "AppStream names for system apps"       "R 'test -f /usr/share/swcatalog/xml/fabos-names.xml'"
chk "KWin runner disabled by real id"       "R 'grep -q krunner_kwinEnabled=false /etc/xdg/krunnerrc'"
chk "wired network managed by NetworkManager" "R 'grep -q renderer:\ NetworkManager /etc/netplan/01-fabos-network-manager.yaml'"
chk "icon theme follows colour scheme"      "R 'grep -q FollowsColorScheme=true /usr/share/icons/FabOS/index.theme'"
# Low-RAM defaults (docs/LOW-RAM.md, ADR-0010) and author metadata (docs/design/BRANDING.md)
chk "zram: generator installed + Fab OS config"  "R 'test -x /usr/lib/systemd/system-generators/zram-generator && test -f /usr/lib/systemd/system/systemd-zram-setup@.service && grep -q \"^\[zram0\]\" /etc/systemd/zram-generator.conf && grep -q \"^zram-size = min(ram / 2, 4096)\" /etc/systemd/zram-generator.conf && grep -q \"^compression-algorithm = zstd\" /etc/systemd/zram-generator.conf'"
chk "zram: swap units generated from config"    "R 'mkdir -p /tmp/zr/etc/systemd /tmp/zr/proc /tmp/zg && cp /etc/systemd/zram-generator.conf /tmp/zr/etc/systemd/ && cp /proc/meminfo /tmp/zr/proc/ && echo > /tmp/zr/proc/cmdline && ZRAM_GENERATOR_ROOT=/tmp/zr /usr/lib/systemd/system-generators/zram-generator /tmp/zg /tmp/zg /tmp/zg >/dev/null 2>&1; test -f /tmp/zg/dev-zram0.swap && test -L /tmp/zg/swap.target.wants/dev-zram0.swap && grep -q ^Priority=100 /tmp/zg/dev-zram0.swap'"
chk "sysctl low-RAM file (swappiness 100)"      "R 'grep -q \"^vm.swappiness = 100\" /etc/sysctl.d/60-fabos-lowram.conf && grep -q \"^vm.vfs_cache_pressure = 50\" /etc/sysctl.d/60-fabos-lowram.conf && grep -q \"^vm.page-cluster = 0\" /etc/sysctl.d/60-fabos-lowram.conf'"
chk "systemd-oomd enabled, 70% pressure limit"  "R 'systemctl is-enabled systemd-oomd.service 2>/dev/null | grep -q ^enabled && grep -q ^DefaultMemoryPressureLimit=70% /etc/systemd/oomd.conf.d/fabos.conf && grep -q ^ManagedOOMMemoryPressureLimit=70% /etc/systemd/system/user@.service.d/90-fabos-oomd.conf'"
chk "baloo file indexing off by default"        "R 'grep -q ^Indexing-Enabled=false /etc/xdg/baloofilerc && grep -q \"^only basic indexing=true\" /etc/xdg/baloofilerc'"
chk "empty session at login"                    "R 'grep -q ^loginMode=emptySession /etc/xdg/ksmserverrc'"
chk "cups on demand (socket+path, no service)"  "R 'systemctl is-enabled cups.socket | grep -q ^enabled && systemctl is-enabled cups.path | grep -q ^enabled && ! systemctl is-enabled cups.service 2>/dev/null | grep -q ^enabled && grep -q ^IdleExitTimeout /etc/cups/cupsd.conf'"
chk "cups-browsed + smartd + motd-news off"     "! R 'systemctl is-enabled cups-browsed.service smartmontools.service motd-news.timer 2>/dev/null' | grep -q ^enabled"
chk "essential services still enabled"          "R 'systemctl is-enabled NetworkManager sddm unattended-upgrades bluetooth avahi-daemon 2>/dev/null' | grep -c ^enabled | grep -q ^5"
chk "aiosd not started at login (opt-in)"       "! R 'systemctl --global is-enabled aiosd.service 2>/dev/null' | grep -q ^enabled"
chk "fabos-agent started at login"              "R 'systemctl --global is-enabled fabos-agent.service' | grep -q ^enabled"
chk "agent daemon imports no SDK/Qt at start"   "! R 'grep -E \"^(import|from) (anthropic|PyQt6|openai|google)\" /usr/lib/fabos/agent/fabos_agentd.py' | grep -q ."
chk "welcome wrapper exits before Python"       "R 'grep -q welcome-done /usr/bin/fabos-welcome && grep -q \"exit 0\" /usr/bin/fabos-welcome'"
chk "SDDM theme Author=Patience AI"             "R 'grep -q \"^Author=Patience AI\" /usr/share/sddm/themes/fabos/metadata.desktop && grep -q ^Email=support@patienceai.in /usr/share/sddm/themes/fabos/metadata.desktop && grep -q ^Website=https://fabos.patienceai.in /usr/share/sddm/themes/fabos/metadata.desktop'"
chk "Plymouth theme names Patience AI"          "R 'grep -q \"by Patience AI\" /usr/share/plymouth/themes/fabos/fabos.plymouth && grep -q ^ModuleName=script /usr/share/plymouth/themes/fabos/fabos.plymouth'"
chk "Patience AI author in every metadata.json" "! R 'grep -L \"\\\"Name\\\": \\\"Patience AI\\\"\" /usr/share/plasma/plasmoids/in.patienceai.fabos.askbar/metadata.json /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/metadata.json /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/metadata.json /usr/share/wallpapers/FabOS/metadata.json /usr/share/plasma/desktoptheme/FabOS/metadata.json' | grep -q ."
chk "icon theme Comment names Patience AI"      "R 'grep -q \"^Comment=.*by Patience AI\" /usr/share/icons/FabOS/index.theme'"
chk "Homepage in every fabos package"           "! R 'for p in fabos-agent fabos-ai fabos-branding fabos-desktop fabos-desktop-meta fabos-feedback fabos-firstboot fabos-updates fabos-welcome; do dpkg -s \$p 2>/dev/null | grep -q \"^Homepage: https://fabos.patienceai.in\" || echo \$p; done' | grep -q ."
chk "os-release vendor + URLs"                  "R 'grep -q \"^VENDOR_NAME=.Patience AI\" /usr/lib/os-release && grep -q ^HOME_URL= /usr/lib/os-release && grep -q ^SUPPORT_URL= /usr/lib/os-release && grep -q ^BUG_REPORT_URL= /usr/lib/os-release'"
chk "about line in Fab OS apps"                 "! R 'grep -L \"Fab OS by Patience AI\" /usr/lib/fabos/welcome/fabos_welcome.py /usr/lib/fabos/updates/fabos_updates.py /usr/lib/fabos/feedback/fabos_feedback.py' | grep -q ."

# Desktop chrome (2026-09-14): Aurorae window frame, monochrome scheme-following status icons, peek-desktop placement, 11 pt UI.
LAYOUT=/usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/layouts/org.kde.plasma.desktop-layout.js
chk "Aurorae FabOS decoration shipped (+Light)" "R 'test -f /usr/share/aurorae/themes/FabOS/metadata.desktop && test -f /usr/share/aurorae/themes/FabOS/decoration.svg && test -f /usr/share/aurorae/themes/FabOS/close.svg && test -f /usr/share/aurorae/themes/FabOS/FabOSrc && test -f /usr/share/aurorae/themes/FabOSLight/FabOSLightrc && test -f /usr/share/aurorae/themes/FabOSLight/decoration.svg'"
chk "decoration SVGs follow the colour scheme" "R 'grep -q ColorScheme-HeaderBackground /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q current-color-scheme /usr/share/aurorae/themes/FabOS/close.svg'"
chk "Aurorae metadata names the KCM entries Fab OS" "R 'grep -q ^Name=Fab\ OS$ /usr/share/aurorae/themes/FabOS/metadata.desktop && grep -q ^Name=Fab\ OS\ Light$ /usr/share/aurorae/themes/FabOSLight/metadata.desktop'"
chk "kwinrc selects the FabOS decoration via Aurorae v2" "R 'grep -q ^library=org.kde.kwin.aurorae.v2$ /etc/xdg/kwinrc && grep -q ^theme=__aurorae__svg__FabOS$ /etc/xdg/kwinrc && grep -q ^BorderSizeAuto=false /etc/xdg/kwinrc && grep -q ^BorderSize=None /etc/xdg/kwinrc'"
chk "look-and-feel defaults select FabOS/FabOSLight (v2)" "R 'grep -q ^theme=__aurorae__svg__FabOS$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/defaults && grep -q ^theme=__aurorae__svg__FabOSLight$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/contents/defaults && grep -q ^library=org.kde.kwin.aurorae.v2$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/defaults && grep -q ^library=org.kde.kwin.aurorae.v2$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/contents/defaults'"
chk "Aurorae v2 engine + its KCM installed"    "R 'test -f /usr/lib/x86_64-linux-gnu/qt6/plugins/org.kde.kdecoration3/org.kde.kwin.aurorae.v2.so && test -f /usr/lib/x86_64-linux-gnu/qt6/plugins/org.kde.kdecoration3.kcm/kcm_auroraedecoration.so'"
chk "fabos-desktop depends on kwin-style-aurorae" "R 'dpkg -s fabos-desktop' | grep ^Depends | grep -q kwin-style-aurorae"
chk "decoration KCM model lists Fab OS (Aurorae v2)" "R 'HOME=/tmp QT_QPA_PLATFORM=offscreen /usr/lib/x86_64-linux-gnu/libexec/kwin-applywindowdecoration --list-themes 2>/dev/null' | grep -q 'Fab OS (theme name: __aurorae__svg__FabOS'"
chk "bottom-right hot corner shows desktop"   "R 'grep -q ^BottomRight=ShowDesktop /etc/xdg/kwinrc'"
chk "peek-desktop is the last dock item, not in the top bar" "[ \$(R 'grep -c showdesktop $LAYOUT') -eq 1 ] && [ \$(R 'grep -n showdesktop $LAYOUT | cut -d: -f1') -gt \$(R 'grep -n \"^var dock\" $LAYOUT | cut -d: -f1') ]"
chk "FabOS mono status icons follow scheme"   "R 'grep -q ColorScheme-Text /usr/share/icons/FabOS/scalable/status/network-wireless-signal-excellent.svg && grep -q current-color-scheme /usr/share/icons/FabOS/scalable/status/network-wireless-connected-100.svg && test -e /usr/share/icons/FabOS/scalable/status/battery-080-charging.svg && test -e /usr/share/icons/FabOS/scalable/status/audio-volume-high.svg && test -e /usr/share/icons/FabOS/scalable/status/battery-profile-performance-symbolic.svg && test -e /usr/share/icons/FabOS/scalable/status/preferences-system-bluetooth.svg && test -e /usr/share/icons/FabOS/scalable/actions/arrow-down.svg && test -e /usr/share/icons/FabOS/scalable/places/user-desktop.svg'"
chk "mono status icons are SVG only (recolourable)" "! R 'ls /usr/share/icons/FabOS/*/status/*.png 2>/dev/null' | grep -q ."
chk "kdeglobals UI font is 11 pt, icons medium" "R 'grep -q \"^font=Inter,11,\" /etc/xdg/kdeglobals && grep -q \"^menuFont=Inter,11,\" /etc/xdg/kdeglobals && grep -q \"^toolBarFont=Inter,11,\" /etc/xdg/kdeglobals && grep -A1 \"^\\[ToolbarIcons\\]\" /etc/xdg/kdeglobals | grep -q ^Size=24'"
chk "clock is bold Inter 13 on one line"      "R 'grep -q \"\\\"fontSize\\\", 13\" $LAYOUT && grep -q \"\\\"dateDisplayFormat\\\", \\\"BesideTime\\\"\" $LAYOUT'"
chk "tray-defaults is executable"             "R 'test -x /usr/lib/fabos/tray-defaults'"
# Built-in offline AI model (2026-09-14, ADR-0011): the GGUF is inside the image with the right size, its licence + README sit
# next to it, the manifest carries the same hash, the on-demand units are shipped and the socket is enabled for every user.
MODEL=/usr/share/fabos/models/qwen2.5-1.5b-instruct-q4_k_m.gguf
MODEL_SHA=6a1a2eb6d15622bf3c96857206351ba97e1af16c30d7a74ee38970e434e9407e
chk "built-in model file present, 1117320736 bytes" "[ \$(R 'stat -c %s $MODEL 2>/dev/null') = 1117320736 ]"
chk "model README records the pinned sha256"      "R 'grep -q $MODEL_SHA /usr/share/fabos/models/README'"
chk "model licence: Apache-2.0 + Alibaba notice" "R 'grep -q \"Apache License\" /usr/share/fabos/models/LICENSE-qwen2.5 && grep -q \"Copyright 2024 Alibaba Cloud\" /usr/share/fabos/models/LICENSE-qwen2.5'"
chk "ai-models.json manifest matches the pin"    "R 'grep -q $MODEL_SHA /usr/share/fabos/ai-models.json && grep -q 1117320736 /usr/share/fabos/ai-models.json && grep -q $MODEL /usr/share/fabos/ai-models.json'"
chk "llama-server present"                       "R 'test -x /usr/bin/llama-server'"
chk "fabos-llama units shipped"                  "R 'test -f /usr/lib/systemd/user/fabos-llama.socket && test -f /usr/lib/systemd/user/fabos-llama-proxy.service && test -f /usr/lib/systemd/user/fabos-llama.service && test -x /usr/lib/fabos/ai/llama-start.sh && test -x /usr/bin/fabos-local-model'"
chk "fabos-llama.socket enabled for all users"   "R 'systemctl --global is-enabled fabos-llama.socket' | grep -q ^enabled"
# (test the captured text, not a negated `| grep -q` pipeline: with pipefail, grep -q's early exit SIGPIPEs podman and `!` turns that into a PASS)
chk "fabos-llama units pass systemd-analyze"     "[ -z \"\$(R 'mkdir -p /tmp/xdg && chmod 700 /tmp/xdg && XDG_RUNTIME_DIR=/tmp/xdg systemd-analyze verify --user /usr/lib/systemd/user/fabos-llama.socket /usr/lib/systemd/user/fabos-llama-proxy.service /usr/lib/systemd/user/fabos-llama.service 2>&1 || echo VERIFY-FAILED' | grep -iE 'error|fail|not found|unknown|ignoring')\" ]"
chk "fabos-local-model status: installed + size ok" "R 'fabos-local-model status' | grep -q '\"installed\": true' && R 'fabos-local-model status' | grep -q '\"size_ok\": true'"
chk "ai.env points at the built-in model"        "R 'grep -q ^AIOS_LLAMA_MODEL=$MODEL /etc/fabos/ai.env' && ! R 'grep -qi download /etc/fabos/ai.env'"

# Voice (2026-09-14): "Hey Fab" wake word (pocketsphinx, offline), whisper.cpp tiny.en model shipped in the image, espeak-ng fallback
chk "voice: CLI, daemon and engines installed"     "R 'test -x /usr/bin/fabos-voice && test -x /usr/lib/fabos/voice/fabos_voiced.py && test -x /usr/bin/pocketsphinx && test -x /usr/bin/whisper-cli && test -x /usr/bin/espeak-ng && test -x /usr/bin/pw-record'"
chk "voice: fabos-voiced user unit enabled"        "R 'systemctl --global is-enabled fabos-voiced.service' | grep -q enabled"
chk "voice: whisper tiny.en model shipped (sha256)" "R 'sha256sum /usr/share/fabos/voice/ggml-tiny.en.bin' | grep -q ^921e4cf8686fdd993dcd081a5da5b6c365bfde1162e72b08d75ac75289920b1f"
chk "voice: dictionary knows the wake phrase"      "R 'grep -q \"^hey HH EY\" /usr/share/pocketsphinx/model/en-us/cmudict-en-us.dict && grep -q \"^fab F AE B\" /usr/share/pocketsphinx/model/en-us/cmudict-en-us.dict'"
chk "voice: status reports offline whisper.cpp"    "R 'fabos-voice status' | grep -q '\"stt\": \"whisper.cpp\"'"
exit $fail
