#!/usr/bin/env bash
# Static checks on the built image: identity, no Canonical branding packages, no snap, legal files present.
set -uo pipefail; PROFILE=${1:-vm}; TAG=fabos:$PROFILE; fail=0
chk() { if eval "$2"; then echo "PASS  $1"; else echo "FAIL  $1"; fail=1; fi; }
R() { podman run --rm "$TAG" bash -c "$1"; }
chk "all fabos packages fully installed"   "! R 'dpkg -l fabos-* | grep -v ^ii | grep -E \"^(i|h|r|u)\"' | grep -q ."
chk "os-release ID=fabos"               "R 'grep -q ^ID=fabos /usr/lib/os-release && grep -q ID_LIKE=.ubuntu /usr/lib/os-release'"
chk "os-release keeps UBUNTU_CODENAME"    "R 'grep -q ^UBUNTU_CODENAME=resolute /usr/lib/os-release'"
chk "lsb_release says FabOS"             "R 'lsb_release -ds' | grep -q 'Fab OS'"
chk "/etc/os-release is a symlink"        "R 'test -L /etc/os-release'"
chk "Ubuntu identity diverted, not lost"  "R 'test -f /usr/lib/os-release.ubuntu && grep -q ^ID=ubuntu /usr/lib/os-release.ubuntu'"
chk "no Canonical artwork packages"       "! R 'dpkg -l ubuntu-wallpapers* plymouth-theme-ubuntu* ubuntu-artwork 2>/dev/null | grep ^ii'"
chk "snapd absent"                        "! R 'dpkg -s snapd 2>/dev/null' >/dev/null"
chk "ubuntu-pro-client absent"            "! R 'dpkg -s ubuntu-pro-client 2>/dev/null' >/dev/null"
chk "plymouth default theme = fabos"     "R 'readlink -f /usr/share/plymouth/themes/default.plymouth' | grep -q themes/fabos/fabos.plymouth"
chk "plymouth script plugin present"      "R 'ls /usr/lib/x86_64-linux-gnu/plymouth/script.so'"
chk "initramfs contains fabos theme"     "R 'lsinitramfs /boot/initrd.img-* | grep -q themes/fabos/fabos.script'"
chk "Inter font installed"                "R 'fc-list | grep -qi Inter-Regular'"
chk "SDDM theme configured"               "R 'grep -q Current=fabos /etc/sddm.conf.d/zz-fabos.conf && test -f /usr/share/sddm/themes/fabos/Main.qml'"
chk "look-and-feel package present"       "R 'test -f /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/defaults'"
chk "wallpaper installed"                 "R 'test -f /usr/share/wallpapers/FabOS/contents/images/1920x1080.png'"
# High-definition assets (2026-09-13): 7 wallpaper sizes light+dark, 4K greeter/splash background, 256 px boot frames,
# bare transparent mark (vector + PNG up to 512 in hicolor, 1024 in pixmaps), scalable/ listed first in the icon theme.
PNGDIM='od -An -tu4 --endian=big -j16 -N8'   # PNG IHDR width/height -> "  W  H" (no python quoting through eval)
chk "wallpapers: 7 sizes, light + dark"     "[ \$(R 'ls /usr/share/wallpapers/FabOS/contents/images/*.png /usr/share/wallpapers/FabOS/contents/images_dark/*.png | wc -l') -eq 14 ]"
chk "wallpaper 4K + 1366x768 present"       "R 'test -f /usr/share/wallpapers/FabOS/contents/images/3840x2160.png && test -f /usr/share/wallpapers/FabOS/contents/images_dark/3840x2160.png && test -f /usr/share/wallpapers/FabOS/contents/images/1366x768.png'"
chk "wallpaper package metadata Fab OS"     "R 'grep -q \"\\\"Name\\\": \\\"Fab OS\\\"\" /usr/share/wallpapers/FabOS/metadata.json && grep -q Apache-2.0 /usr/share/wallpapers/FabOS/metadata.json'"
chk "SDDM background is 3840x2160"          "R \"$PNGDIM /usr/share/sddm/themes/fabos/background.png\" | tr -s ' ' x | grep -q x3840x2160"
chk "SDDM + KSplash use the vector mark"    "R 'test -f /usr/share/sddm/themes/fabos/mark.svg && test -f /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/splash/images/mark.svg'"
chk "lock screen crops, never stretches"    "R 'grep -q ^FillMode=2 /etc/xdg/kscreenlockerrc'"
chk "plymouth frames are 256 px"            "R \"$PNGDIM /usr/share/plymouth/themes/fabos/spinner-00.png\" | tr -s ' ' x | grep -q x256x256"
chk "plymouth script scales to the screen"  "R 'grep -q \"Window.GetHeight()\" /usr/share/plymouth/themes/fabos/fabos.script && grep -q \"Scale(logo_h\" /usr/share/plymouth/themes/fabos/fabos.script'"
chk "hicolor fabos: svg + 512 png"          "R 'test -f /usr/share/icons/hicolor/scalable/apps/fabos.svg && test -f /usr/share/icons/hicolor/scalable/apps/fabos-symbolic.svg && test -f /usr/share/icons/hicolor/512x512/apps/fabos.png'"
chk "hicolor fabos.svg has no tile"         "! R 'grep -q \"<rect width=\\\"64\\\"\" /usr/share/icons/hicolor/scalable/apps/fabos.svg'"
chk "pixmaps fabos.png is 1024 px"          "R \"$PNGDIM /usr/share/pixmaps/fabos.png\" | tr -s ' ' x | grep -q x1024x1024"
chk "default avatar = fabos-face.png"       "R 'readlink /usr/share/sddm/faces/.face.icon' | grep -q fabos-face.png"
chk "FabOS icon theme: fabos + symbolic"    "R 'test -f /usr/share/icons/FabOS/scalable/apps/fabos.svg && test -f /usr/share/icons/FabOS/scalable/apps/fabos-symbolic.svg && test -f /usr/share/icons/FabOS/512x512/apps/fabos.png'"
chk "FabOS index.theme: scalable first, follows scheme" "R 'grep -qE \"^Directories=scalable/status,.*scalable/apps,16x16/apps\" /usr/share/icons/FabOS/index.theme && grep -q ^FollowsColorScheme=true /usr/share/icons/FabOS/index.theme'"
chk "3D logo shipped"                     "R 'test -s /usr/share/fabos/3d/fabos-mark.glb'"
chk "aios runs"                           "R 'aios settings list' >/dev/null 2>&1"
chk "llama-cli present"                   "R 'test -x /usr/bin/llama-cli'"
chk "copyright files retained (>300)"     "[ \$(R 'find /usr/share/doc -name copyright | wc -l') -gt 300 ]"
chk "source offer shipped on system"      "R 'test -f /usr/share/doc/fabos-branding/SOURCE-OFFER'"
chk "kernel + initrd present"             "R 'ls /boot/vmlinuz-* /boot/initrd.img-*'"
chk "sddm enabled"                        "R 'systemctl is-enabled sddm' | grep -q enabled"
chk "FabOS Plasma theme installed"        "R 'test -f /usr/share/plasma/desktoptheme/FabOS/metadata.json && test -f /usr/share/plasma/desktoptheme/FabOS/dialogs/background.svg'"
chk "FabOS icon theme has Settings icons"  "R 'test -e /usr/share/icons/FabOS/48x48/apps/preferences-system-network.png'"
chk "Fab OS session entry (no Plasma name)" "R 'grep -q ^Name=Fab\ OS /usr/local/share/wayland-sessions/fabos.desktop && grep -q SessionDir=/usr/local/share/wayland-sessions /etc/sddm.conf.d/zz-fabos.conf'"
# 2026-09-15 (ADR-0015): the two wallet checks below used to assert the Fab Wallet KCM binary and menu override; the wallet is
# now removed, so they assert the opposite (rewritten in place — the old expectation is the defect).
chk "no wallet: kwalletmanager + its KCM absent"  "! R 'dpkg -s kwalletmanager 2>/dev/null' >/dev/null && ! R 'test -f /usr/lib/x86_64-linux-gnu/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwallet5.so'"
chk "no wallet: no wallet menu entry or override" "[ -z \"\$(R 'ls /usr/share/applications/org.kde.kwalletmanager.desktop /usr/local/share/applications/org.kde.kwalletmanager.desktop 2>/dev/null')\" ]"
chk "no visible KDE names in launcher"     "! R 'grep -lE \"^Name=.*KDE\" /usr/share/applications/*.desktop | while read f; do b=\$(basename \$f); test -f /usr/local/share/applications/\$b || echo \$b; done' | grep -q ."
chk "updates app + polkit + timer"         "R 'test -x /usr/bin/fabos-updates && test -f /usr/share/polkit-1/actions/in.patienceai.fabos.updates.policy && systemctl is-enabled fabos-update-check.timer' | grep -q enabled"
chk "unattended-upgrades allows Fab OS"    "R 'grep -q \"Patience AI:loom\" /etc/apt/apt.conf.d/52fabos-unattended'"
chk "KRunner agent plugin registered"      "R 'test -f /usr/share/krunner/dbusplugins/fabos-runner.desktop && test -f /usr/share/dbus-1/services/in.patienceai.fabos.runner.service'"
chk "file-manager Ask Fab OS action"       "R 'test -f /usr/share/kio/servicemenus/fabos-ask.desktop'"
chk "browser: firefox from Mozilla (not the snap shim), brave-browser absent" "R 'dpkg -s firefox' | grep -q '^Maintainer: Mozilla' && ! R 'dpkg -s brave-browser 2>/dev/null' >/dev/null"   # 2026-09-15 (ADR-0018): Firefox is back; the ADR-0016 Brave expectation was the defect
chk "first-boot provisioning shipped"      "R 'test -x /usr/lib/fabos/firstboot.sh && systemctl is-enabled fabos-firstboot.service 2>/dev/null | grep -qE \"enabled|masked\"'"
chk "en@fabos catalogs generated"          "R 'test -s /usr/local/share/locale/en@fabos/LC_MESSAGES/konsole.mo && test -s /usr/local/share/locale/en@fabos/LC_MESSAGES/dolphin.mo'"
chk "session prefers en@fabos"              "R 'test -f /etc/xdg/plasma-workspace/env/50-fabos-language.sh'"
chk "ki18n renames Kate -> Fab Editor"       "R 'HOME=/tmp LANGUAGE=en@fabos:en_US QT_QPA_PLATFORM=offscreen kate --help 2>/dev/null' | grep -q 'Fab Editor - Advanced Text Editor'"
chk "Discover binary never byte-patched"     "R 'test ! -f /usr/bin/plasma-discover.fabos-orig'"
chk "Konsole binaries never byte-patched"      "R 'test ! -f /usr/bin/konsole.fabos-orig && test ! -f /usr/lib/x86_64-linux-gnu/libkonsoleprivate.so.25.12.3.fabos-orig'"
chk "mime override + hidden Software Sources"  "R 'test -f /usr/share/mime/packages/Override.xml && grep -q Hidden=true /usr/local/share/applications/software-properties-qt.desktop'"
chk "light + dark Fab look-and-feel"        "R 'test -f /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/contents/defaults && grep -q DefaultLightLookAndFeel=in.patienceai.fabos.light.desktop /etc/xdg/kdeglobals'"
chk "KDE donation nag off"                  "R 'grep -q autoload=false /etc/xdg/kded6rc'"
chk "no ubuntu account"                     "! R 'grep -q ^ubuntu: /etc/passwd'"
chk "no unminimize MOTD"                    "R 'test ! -f /etc/update-motd.d/60-unminimize'"
chk "Desktop Actions keep their own names"   "! R 'awk \"/^\\[Desktop Action/{a=1} a && /^Name=Fab Terminal/{print}\" /usr/local/share/applications/org.kde.konsole.desktop' | grep -q ."
chk "shortcut component names overridden"    "R 'grep -q ^Name=Fab\ Terminal /usr/local/share/kglobalaccel/org.kde.konsole.desktop'"
chk "Ubuntu web shortcut hidden"            "R 'grep -q Hidden=true /usr/local/share/kf6/searchproviders/ubuntu.desktop'"
chk "AppStream names for system apps"       "R 'test -f /usr/share/swcatalog/xml/fabos-names.xml'"
chk "KWin runner disabled by real id"       "R 'grep -q krunner_kwinEnabled=false /etc/xdg/krunnerrc'"
chk "wired network managed by NetworkManager" "R 'grep -q renderer:\ NetworkManager /etc/netplan/01-fabos-network-manager.yaml'"
chk "icon theme follows colour scheme"      "R 'grep -q FollowsColorScheme=true /usr/share/icons/FabOS/index.theme'"
# Low-RAM defaults (docs/LOW-RAM.md, ADR-0010) and author metadata (docs/design/BRANDING.md)
chk "zram: generator installed + Fab OS config"  "R 'test -x /usr/lib/systemd/system-generators/zram-generator && test -f /usr/lib/systemd/system/systemd-zram-setup@.service && grep -q \"^\[zram0\]\" /etc/systemd/zram-generator.conf && grep -q \"^zram-size = min(ram / 2, 4096)\" /etc/systemd/zram-generator.conf && grep -q \"^compression-algorithm = zstd\" /etc/systemd/zram-generator.conf'"
chk "zram: swap units generated from config"    "R 'mkdir -p /tmp/zr/etc/systemd /tmp/zr/proc /tmp/zg && cp /etc/systemd/zram-generator.conf /tmp/zr/etc/systemd/ && cp /proc/meminfo /tmp/zr/proc/ && echo > /tmp/zr/proc/cmdline && ZRAM_GENERATOR_ROOT=/tmp/zr /usr/lib/systemd/system-generators/zram-generator /tmp/zg /tmp/zg /tmp/zg >/dev/null 2>&1; test -f /tmp/zg/dev-zram0.swap && test -L /tmp/zg/swap.target.wants/dev-zram0.swap && grep -q ^Priority=100 /tmp/zg/dev-zram0.swap'"
chk "sysctl low-RAM file (swappiness 100)"      "R 'grep -q \"^vm.swappiness = 100\" /etc/sysctl.d/60-fabos-lowram.conf && grep -q \"^vm.vfs_cache_pressure = 50\" /etc/sysctl.d/60-fabos-lowram.conf && grep -q \"^vm.page-cluster = 0\" /etc/sysctl.d/60-fabos-lowram.conf'"
chk "systemd-oomd enabled, 70% pressure limit"  "R 'systemctl is-enabled systemd-oomd.service 2>/dev/null | grep -q ^enabled && grep -q ^DefaultMemoryPressureLimit=70% /etc/systemd/oomd.conf.d/fabos.conf && grep -q ^ManagedOOMMemoryPressureLimit=70% /etc/systemd/system/user@.service.d/90-fabos-oomd.conf'"
chk "baloo file indexing off by default"        "R 'grep -q ^Indexing-Enabled=false /etc/xdg/baloofilerc && grep -q \"^only basic indexing=true\" /etc/xdg/baloofilerc'"
chk "empty session at login"                    "R 'grep -q ^loginMode=emptySession /etc/xdg/ksmserverrc'"
chk "cups on demand (socket+path, no service)"  "R 'systemctl is-enabled cups.socket | grep -q ^enabled && systemctl is-enabled cups.path | grep -q ^enabled && ! systemctl is-enabled cups.service 2>/dev/null | grep -q ^enabled && grep -q ^IdleExitTimeout /etc/cups/cupsd.conf'"
chk "cups-browsed + smartd + motd-news off"     "! R 'systemctl is-enabled cups-browsed.service smartmontools.service motd-news.timer 2>/dev/null' | grep -q ^enabled"
chk "essential services still enabled"          "R 'systemctl is-enabled NetworkManager sddm unattended-upgrades bluetooth 2>/dev/null' | grep -c ^enabled | grep -q ^4"   # avahi-daemon is off by default since ADR-0017 (mDNS discovery surface)
chk "aiosd not started at login (opt-in)"       "! R 'systemctl --global is-enabled aiosd.service 2>/dev/null' | grep -q ^enabled"
chk "fabos-agent started at login"              "R 'systemctl --global is-enabled fabos-agent.service' | grep -q ^enabled"
chk "agent daemon imports no SDK/Qt at start"   "! R 'grep -E \"^(import|from) (anthropic|PyQt6|openai|google)\" /usr/lib/fabos/agent/fabos_agentd.py' | grep -q ."
chk "welcome wrapper exits before Python"       "R 'grep -q welcome-done /usr/bin/fabos-welcome && grep -q \"exit 0\" /usr/bin/fabos-welcome'"
chk "SDDM theme Author=Patience AI"             "R 'grep -q \"^Author=Patience AI\" /usr/share/sddm/themes/fabos/metadata.desktop && grep -q ^Email=support@patienceai.in /usr/share/sddm/themes/fabos/metadata.desktop && grep -q ^Website=https://fabos.patienceai.in /usr/share/sddm/themes/fabos/metadata.desktop'"
chk "Plymouth theme names Patience AI"          "R 'grep -q \"by Patience AI\" /usr/share/plymouth/themes/fabos/fabos.plymouth && grep -q ^ModuleName=script /usr/share/plymouth/themes/fabos/fabos.plymouth'"
chk "Patience AI author in every metadata.json" "! R 'grep -L \"\\\"Name\\\": \\\"Patience AI\\\"\" /usr/share/plasma/plasmoids/in.patienceai.fabos.askbar/metadata.json /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/metadata.json /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/metadata.json /usr/share/wallpapers/FabOS/metadata.json /usr/share/plasma/desktoptheme/FabOS/metadata.json' | grep -q ."
chk "icon theme Comment names Patience AI"      "R 'grep -q \"^Comment=.*by Patience AI\" /usr/share/icons/FabOS/index.theme'"
chk "Homepage in every fabos package"           "! R 'for p in fabos-agent fabos-ai fabos-branding fabos-desktop fabos-desktop-meta fabos-feedback fabos-firstboot fabos-updates fabos-welcome fabos-voice; do dpkg -s \$p 2>/dev/null | grep -q \"^Homepage: https://fabos.patienceai.in\" || echo \$p; done' | grep -q ."
chk "os-release vendor + URLs"                  "R 'grep -q \"^VENDOR_NAME=.Patience AI\" /usr/lib/os-release && grep -q ^HOME_URL= /usr/lib/os-release && grep -q ^SUPPORT_URL= /usr/lib/os-release && grep -q ^BUG_REPORT_URL= /usr/lib/os-release'"
# NB: negative `grep -L` checks end the container command with `; true` so the pipeline status (pipefail) is that of the
# outer `grep -q .` alone, whatever exit status this grep version gives -L.
chk "about line in Fab OS apps (with ™)"         "! R 'grep -L \"Fab OS™ by Patience AI\" /usr/lib/fabos/welcome/fabos_welcome.py /usr/lib/fabos/updates/fabos_updates.py /usr/lib/fabos/feedback/fabos_feedback.py; true' | grep -q ."
chk "Welcome first page says Fab OS™"           "R 'grep -q \"Page(\\\"Welcome to Fab OS™\\\"\" /usr/lib/fabos/welcome/fabos_welcome.py'"
chk "™ never in machine ids"                    "! R 'grep -l ™ /usr/lib/os-release /etc/lsb-release /var/lib/dpkg/status /usr/share/applications/fabos-*.desktop 2>/dev/null; true' | grep -q ."

# Desktop chrome (2026-09-14): Aurorae window frame, monochrome scheme-following status icons, peek-desktop placement, 11 pt UI.
LAYOUT=/usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/layouts/org.kde.plasma.desktop-layout.js
chk "Aurorae FabOS decoration shipped (+Light)" "R 'test -f /usr/share/aurorae/themes/FabOS/metadata.desktop && test -f /usr/share/aurorae/themes/FabOS/decoration.svg && test -f /usr/share/aurorae/themes/FabOS/close.svg && test -f /usr/share/aurorae/themes/FabOS/FabOSrc && test -f /usr/share/aurorae/themes/FabOSLight/FabOSLightrc && test -f /usr/share/aurorae/themes/FabOSLight/decoration.svg'"
chk "decoration SVGs follow the colour scheme" "R 'grep -q ColorScheme-HeaderBackground /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q current-color-scheme /usr/share/aurorae/themes/FabOS/close.svg'"
chk "Aurorae metadata names the KCM entries Fab OS" "R 'grep -q ^Name=Fab\ OS$ /usr/share/aurorae/themes/FabOS/metadata.desktop && grep -q ^Name=Fab\ OS\ Light$ /usr/share/aurorae/themes/FabOSLight/metadata.desktop'"
chk "kwinrc selects the FabOS decoration via Aurorae v2" "R 'grep -q ^library=org.kde.kwin.aurorae.v2$ /etc/xdg/kwinrc && grep -q ^theme=__aurorae__svg__FabOS$ /etc/xdg/kwinrc && grep -q ^BorderSizeAuto=false /etc/xdg/kwinrc && grep -q ^BorderSize=None /etc/xdg/kwinrc'"
chk "look-and-feel defaults select FabOS/FabOSLight (v2)" "R 'grep -q ^theme=__aurorae__svg__FabOS$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/defaults && grep -q ^theme=__aurorae__svg__FabOSLight$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/contents/defaults && grep -q ^library=org.kde.kwin.aurorae.v2$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/defaults && grep -q ^library=org.kde.kwin.aurorae.v2$ /usr/share/plasma/look-and-feel/in.patienceai.fabos.light.desktop/contents/defaults'"
chk "Aurorae v2 engine + its KCM installed"    "R 'test -f /usr/lib/x86_64-linux-gnu/qt6/plugins/org.kde.kdecoration3/org.kde.kwin.aurorae.v2.so && test -f /usr/lib/x86_64-linux-gnu/qt6/plugins/org.kde.kdecoration3.kcm/kcm_auroraedecoration.so'"
chk "fabos-desktop depends on kwin-style-aurorae" "R 'dpkg -s fabos-desktop' | grep ^Depends | grep -q kwin-style-aurorae"
chk "decoration KCM model lists Fab OS (Aurorae v2)" "R 'HOME=/tmp QT_QPA_PLATFORM=offscreen /usr/lib/x86_64-linux-gnu/libexec/kwin-applywindowdecoration --list-themes 2>/dev/null' | grep -q 'Fab OS (theme name: __aurorae__svg__FabOS'"
chk "bottom-right hot corner shows desktop"   "R 'grep -q ^BottomRight=ShowDesktop /etc/xdg/kwinrc'"
chk "peek-desktop is the last dock item (drawn by the Fab OS dock at the icons' size), no stock showdesktop applet" "R 'grep -q \"tasks.writeConfig(\\\"showPeek\\\", true)\" $LAYOUT' && [ -z \"\$(R 'grep showdesktop $LAYOUT')\" ]"
chk "FabOS mono status icons follow scheme"   "R 'grep -q ColorScheme-Text /usr/share/icons/FabOS/scalable/status/network-wireless-signal-excellent.svg && grep -q current-color-scheme /usr/share/icons/FabOS/scalable/status/network-wireless-connected-100.svg && test -e /usr/share/icons/FabOS/scalable/status/battery-080-charging.svg && test -e /usr/share/icons/FabOS/scalable/status/audio-volume-high.svg && test -e /usr/share/icons/FabOS/scalable/status/battery-profile-performance-symbolic.svg && test -e /usr/share/icons/FabOS/scalable/status/preferences-system-bluetooth.svg && test -e /usr/share/icons/FabOS/scalable/actions/arrow-down.svg && test -e /usr/share/icons/FabOS/scalable/places/user-desktop.svg'"
chk "mono status icons are SVG only (recolourable)" "! R 'ls /usr/share/icons/FabOS/*/status/*.png 2>/dev/null' | grep -q ."
chk "kdeglobals UI font is 11 pt, icons medium" "R 'grep -q \"^font=Inter,11,\" /etc/xdg/kdeglobals && grep -q \"^menuFont=Inter,11,\" /etc/xdg/kdeglobals && grep -q \"^toolBarFont=Inter,11,\" /etc/xdg/kdeglobals && grep -A1 \"^\\[ToolbarIcons\\]\" /etc/xdg/kdeglobals | grep -q ^Size=24'"
chk "clock is the Fab OS clock (Inter 700, one line 'ddd d MMM · time', size = BAR_SIZE); stock digital clock gone" "R 'grep -q \"top.addWidget(\\\"in.patienceai.fabos.clock\\\")\" $LAYOUT && grep -q \"clock.writeConfig(\\\"barSize\\\", BAR_SIZE)\" $LAYOUT && grep -q \"clock.writeConfig(\\\"dateFormat\\\", \\\"ddd d MMM\\\")\" $LAYOUT && test -f /usr/share/plasma/plasmoids/in.patienceai.fabos.clock/contents/ui/main.qml' && [ -z \"\$(R 'grep org.kde.plasma.digitalclock $LAYOUT')\" ]"
chk "tray-defaults is executable"             "R 'test -x /usr/lib/fabos/tray-defaults'"
# Built-in offline AI model (2026-09-14, ADR-0011): the GGUF is inside the image with the right size, its licence + README sit
# next to it, the manifest carries the same hash, the on-demand units are shipped and the socket is enabled for every user.
MODEL=/usr/share/fabos/models/qwen2.5-1.5b-instruct-q4_k_m.gguf
MODEL_SHA=6a1a2eb6d15622bf3c96857206351ba97e1af16c30d7a74ee38970e434e9407e
chk "built-in model file present, 1117320736 bytes" "[ \$(R 'stat -c %s $MODEL 2>/dev/null') = 1117320736 ]"
chk "model README records the pinned sha256"      "R 'grep -q $MODEL_SHA /usr/share/fabos/models/README'"
chk "model licence: Apache-2.0 + Alibaba notice" "R 'grep -q \"Apache License\" /usr/share/fabos/models/LICENSE-qwen2.5 && grep -q \"Copyright 2024 Alibaba Cloud\" /usr/share/fabos/models/LICENSE-qwen2.5'"
chk "ai-models.json manifest matches the pin"    "R 'grep -q $MODEL_SHA /usr/share/fabos/ai-models.json && grep -q 1117320736 /usr/share/fabos/ai-models.json && grep -q $MODEL /usr/share/fabos/ai-models.json'"
chk "llama-server present"                       "R 'test -x /usr/bin/llama-server'"
chk "fabos-llama units shipped"                  "R 'test -f /usr/lib/systemd/user/fabos-llama.socket && test -f /usr/lib/systemd/user/fabos-llama-proxy.service && test -f /usr/lib/systemd/user/fabos-llama.service && test -x /usr/lib/fabos/ai/llama-start.sh && test -x /usr/bin/fabos-local-model'"
chk "fabos-llama.socket enabled for all users"   "R 'systemctl --global is-enabled fabos-llama.socket' | grep -q ^enabled"
# (test the captured text, not a negated `| grep -q` pipeline: with pipefail, grep -q's early exit SIGPIPEs podman and `!` turns that into a PASS)
chk "fabos-llama units pass systemd-analyze"     "[ -z \"\$(R 'mkdir -p /tmp/xdg && chmod 700 /tmp/xdg && XDG_RUNTIME_DIR=/tmp/xdg systemd-analyze verify --user /usr/lib/systemd/user/fabos-llama.socket /usr/lib/systemd/user/fabos-llama-proxy.service /usr/lib/systemd/user/fabos-llama.service 2>&1 || echo VERIFY-FAILED' | grep -iE 'error|fail|not found|unknown|ignoring')\" ]"
chk "fabos-local-model status: installed + size ok" "R 'fabos-local-model status' | grep -q '\"installed\": true' && R 'fabos-local-model status' | grep -q '\"size_ok\": true'"
chk "ai.env points at the built-in model"        "R 'grep -q ^AIOS_LLAMA_MODEL=$MODEL /etc/fabos/ai.env' && ! R 'grep -qi download /etc/fabos/ai.env'"

# Voice (2026-09-14): "Hey Fab" wake word (pocketsphinx, offline), whisper.cpp tiny.en model shipped in the image, espeak-ng fallback
chk "voice: CLI, daemon and engines installed"     "R 'test -x /usr/bin/fabos-voice && test -x /usr/lib/fabos/voice/fabos_voiced.py && test -x /usr/bin/pocketsphinx && test -x /usr/bin/whisper-cli && test -x /usr/bin/espeak-ng && test -x /usr/bin/pw-record'"
chk "voice: fabos-voiced user unit enabled"        "R 'systemctl --global is-enabled fabos-voiced.service' | grep -q enabled"
chk "voice: whisper tiny.en model shipped (sha256)" "R 'sha256sum /usr/share/fabos/voice/ggml-tiny.en.bin' | grep -q ^921e4cf8686fdd993dcd081a5da5b6c365bfde1162e72b08d75ac75289920b1f"
chk "voice: dictionary knows the wake phrase"      "R 'grep -q \"^hey HH EY\" /usr/share/pocketsphinx/model/en-us/cmudict-en-us.dict && grep -q \"^fab F AE B\" /usr/share/pocketsphinx/model/en-us/cmudict-en-us.dict'"
chk "voice: status reports offline whisper.cpp"    "R 'fabos-voice status' | grep -q '\"stt\": \"whisper.cpp\"'"

# Firewall on by default, window snapping + Snap Assist, package revision (2026-09-14; ADR-0013, brand.conf PKG_REVISION)
chk "ufw on: ENABLED=yes, unit enabled, deny in / allow out" "R 'grep -q ^ENABLED=yes$ /etc/ufw/ufw.conf && systemctl is-enabled ufw | grep -q ^enabled && grep -q ^DEFAULT_INPUT_POLICY=.DROP /etc/default/ufw && grep -q ^DEFAULT_OUTPUT_POLICY=.ACCEPT /etc/default/ufw'"
chk "iso profile: no SSH server, no ufw rules"           "[ \"$PROFILE\" != iso ] || ! R 'dpkg -s openssh-server 2>/dev/null | grep ^Package; grep -c \"^-A ufw-user-input\" /etc/ufw/user.rules' | grep -qE '^Package|^[1-9]'"
chk "vm profile: exactly one ufw rule (22/tcp), v4 + v6" "[ \"$PROFILE\" != vm ] || R 'test \$(grep -c \"^-A ufw-user-input\" /etc/ufw/user.rules) -eq 1 && grep -q \"^-A ufw-user-input -p tcp --dport 22 -j ACCEPT\" /etc/ufw/user.rules && test \$(grep -c \"^-A ufw6-user-input\" /etc/ufw/user6.rules) -eq 1'"
chk "snap assist KWin script shipped + enabled"          "R 'test -f /usr/share/kwin/scripts/fabos-snap-assist/contents/code/main.js && grep -q \"\\\"Id\\\": \\\"fabos-snap-assist\\\"\" /usr/share/kwin/scripts/fabos-snap-assist/metadata.json && grep -q \"\\\"Name\\\": \\\"Patience AI\\\"\" /usr/share/kwin/scripts/fabos-snap-assist/metadata.json && grep -q ^fabos-snap-assistEnabled=true /etc/xdg/kwinrc'"
chk "edge tiling: halves, quarter corners, maximise"     "R 'grep -q ^ElectricBorderTiling=true /etc/xdg/kwinrc && grep -q ^ElectricBorderCornerRatio=0.25 /etc/xdg/kwinrc && grep -q ^ElectricBorderMaximize=true /etc/xdg/kwinrc && grep -q ^ElectricBorderDelay=150 /etc/xdg/kwinrc'"
chk "all 10 fabos packages at 1.0-5 in the manifest"     "[ \$(R 'grep -c -P \"^fabos-[a-z-]+\\t1\\.0-5\$\" /usr/share/fabos/manifest.txt') -eq 10 ]"

# Forbidden third-party product names (owner rule): never in UI strings, QML, Python UI, desktop files, website or docs.
# "OpenAI" is allowed only as a provider label: the daemon's PROVIDERS table, Fab AI Controls' provider dropdown/help
# text, the welcome wizard's provider list, the ask bar's "add a provider" hint (main.qml: 'Claude, OpenAI, Gemini or a
# local model' — a provider-label list; owner may drop this entry if the ask-bar track rewords it), README's provider list,
# licence/attribution files.
SRC=$(cd "$(dirname "$0")/.." && pwd)
FORBID='ChatGPT|SnowUI|Sora|DALL.E|Upgrade plan|can make mistakes'
OPENAI_OK='fabos_agentd\.py$|command_center\.py$|fabos_welcome\.py$|in\.patienceai\.fabos\.askbar/contents/ui/main\.qml$|(^|/)README\.md$|ATTRIBUTIONS\.md$|LICENSING\.md$|THIRD_PARTY_LICENSES/|(^|/)legal/|/copyright$'   # copyright files carry upstream MIT notices verbatim (whisper weights)
chk "no forbidden product names in the source tree"     "! grep -rIn -E '$FORBID' $SRC/packages $SRC/website $SRC/brand $SRC/docs | grep -q ."
chk "no forbidden product names in the image"           "! R 'grep -rIn -E \"$FORBID\" /usr/share/fabos /usr/lib/fabos /usr/share/plasma /usr/share/applications 2>/dev/null; true' | grep -q ."
chk "OpenAI only as a provider label (source tree)"     "! grep -rIl OpenAI $SRC/packages $SRC/website $SRC/brand $SRC/docs $SRC/README.md | grep -vE '$OPENAI_OK' | grep -q ."
chk "OpenAI only as a provider label (image)"           "! R 'grep -rIl OpenAI /usr/share/fabos /usr/lib/fabos /usr/share/plasma /usr/share/applications 2>/dev/null; true' | grep -vE '$OPENAI_OK' | grep -q ."
chk "no files named after those products"              "! find $SRC/packages $SRC/website \( -iname '*chatgpt*' -o -iname '*openai*' -o -iname '*snowui*' \) | grep -q ."

# No wallet, rounded window corners, browser source, security posture (2026-09-15; ADR-0015, ADR-0016 → ADR-0018). The wallet, PAM,
# browser and mimeapps items only pass on an image built from this Containerfile (the v1.0.3 image still has Brave, ADR-0016).
chk "kwalletrc: Enabled=false, Launch Manager=false, no Auto Allow" "R 'grep -q ^Enabled=false$ /etc/xdg/kwalletrc && grep -q \"^Launch Manager=false\" /etc/xdg/kwalletrc' && [ -z \"\$(R 'grep -i \"Auto Allow\" /etc/xdg/kwalletrc')\" ]"
chk "kwalletmanager pinned out (ksshaskpass/libqt6keychain1 Recommend it)" "R 'grep -q kwalletmanager /etc/apt/preferences.d/00-fabos-blocklist'"
chk "pam_kwallet removed from the SDDM PAM stack"        "[ -z \"\$(R 'grep pam_kwallet /etc/pam.d/sddm')\" ]"
chk "decoration: notch geometry — L-shaped shadow paths (radius 20: 48/104, or radius 14: 42/92) OR the flat frame's alpha-1/255 carrier (2026-09-16); desc names the notch" "R 'grep -q notch /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q -e \"d=\\\"M0 0H48V28H28V48H0Z\\\"\" -e \"d=\\\"M0 0H42V28H28V42H0Z\\\"\" -e \"fill-opacity:0.004\" /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q -e \"d=\\\"M56 0H104V48H76V28H56Z\\\"\" -e \"d=\\\"M50 0H92V42H64V28H50Z\\\"\" -e \"fill-opacity:0.004\" /usr/share/aurorae/themes/FabOS/decoration.svg'"   # 2026-09-15 (ADR-0019): accepts the radius-20 (48/104) or the radius-14 (42/92) notch geometry — nothing removed or weakened; the strict radius-14 assertion is the appended "Aurorae top arcs are radius 14" check. 2026-09-16 (ADR-0019 amendment): also accepts the flat frame, whose notch carries the alpha-1/255 carrier instead of L-shaped shadow paths; the strict flat-frame assertions are the appended "one shadow" checks
chk "decoration: frame shadow — EITHER tapered by a luminance mask (taperTL/TRi, not mask-*) OR no frame shadow at all (flat frame: no gradient/mask/filter, carrier fill; 2026-09-16)" "R '{ grep -q \"mask=\\\"url(#taperTL)\\\"\" /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q \"mask=\\\"url(#taperTRi)\\\"\" /usr/share/aurorae/themes/FabOS/decoration.svg; } || { ! grep -q -E \"linearGradient|radialGradient|<mask|<filter\" /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q fill-opacity:0.004 /usr/share/aurorae/themes/FabOS/decoration.svg; }'"   # 2026-09-16 (ADR-0019 amendment): the tapered frame shadow is gone because the KWin effect draws the only shadow; the check now also accepts the flat frame (no gradient/mask/filter, carrier fill)
chk "decoration: no mask-* elements (Aurorae uses them for blur only)" "[ -z \"\$(R 'grep -o \"id=\\\"mask-\" /usr/share/aurorae/themes/FabOS/decoration.svg')\" ]"
chk "decoration: buttons keep 3 px rounded strokes"     "R 'grep -q \"stroke-width=\\\"3\\\"\" /usr/share/aurorae/themes/FabOS/close.svg && grep -q \"stroke-width=\\\"3\\\"\" /usr/share/aurorae/themes/FabOS/maximize.svg && grep -q stroke-linecap=.round /usr/share/aurorae/themes/FabOS/minimize.svg'"
chk "no world-writable files/dirs under /usr/lib/fabos, /usr/share/fabos" "[ -z \"\$(R 'find /usr/lib/fabos /usr/share/fabos -xdev \( -type f -o -type d \) -perm -0002')\" ]"
# Privileged files: the image's FULL setuid / setgid / file-capability lists must be subsets of these allowlists — Ubuntu's stock set as
# measured on the 2026-09-14 vm + iso images (`find / -xdev -perm -4000 -type f`, `-perm -2000`, `getcap -r /`) plus the ONE non-stock
# nothing else: Firefox has no setuid helper (Brave's chrome-sandbox left with Brave, ADR-0018). Any new entry anywhere in the image fails; a missing one does not
# (the vm profile has no newgrp/mount.cifs). Extend the lists only with a SECURITY.md entry.
SUID_OK='^(/usr/bin/(chfn|chsh|fusermount3|gpasswd|mount|newgrp|ntfs-3g|passwd|pkexec|su|sudo\.ws|umount)|/usr/lib/dbus-1\.0/dbus-daemon-launch-helper|/usr/lib/openssh/ssh-keysign|/usr/sbin/mount\.cifs)$'
SGID_OK='^(/usr/bin/(chage|expiry|ssh-agent)|/usr/sbin/(pam_extrausers_chkpwd|unix_chkpwd))$'
CAPS_OK='^(/usr/bin/kwin_wayland cap_sys_nice=ep|/usr/bin/ping cap_net_raw=ep|/usr/lib/x86_64-linux-gnu/gstreamer1\.0/gstreamer-1\.0/gst-ptp-helper cap_net_bind_service,cap_net_admin,cap_sys_nice=ep|/usr/lib/x86_64-linux-gnu/libexec/ksysguard/ksgrd_network_helper cap_net_raw=ep|/usr/lib/x86_64-linux-gnu/libexec/org_kde_powerdevil cap_wake_alarm=ep)$'
chk "setuid files: Ubuntu stock set only (no browser sandbox helper)" "[ -z \"\$(R 'find / -xdev -perm -4000 -type f 2>/dev/null' | grep -vE '$SUID_OK')\" ]"
chk "setgid files: Ubuntu stock set only"                       "[ -z \"\$(R 'find / -xdev -perm -2000 -type f 2>/dev/null' | grep -vE '$SGID_OK')\" ]"
chk "file capabilities: Ubuntu stock set only"                  "[ -z \"\$(R 'getcap -r / 2>/dev/null' | grep -vE '$CAPS_OK')\" ]"
chk "no Fab OS file is setuid/setgid or carries a capability"   "[ -z \"\$(R 'find /usr/lib/fabos /usr/share/fabos /usr/bin/fabos* /usr/bin/aios -xdev \( -perm -4000 -o -perm -2000 \) -type f 2>/dev/null; getcap -r /usr/lib/fabos /usr/share/fabos 2>/dev/null')\" ]"
chk "browser: Firefox adds no setuid file; brave-browser/brave-keyring, /opt/brave.com, brave sysctl + defaults gone" "[ -z \"\$(R 'find /usr/lib/firefox -perm -4000 -type f 2>/dev/null; dpkg -l brave-browser brave-keyring 2>/dev/null | grep ^ii; ls -d /opt/brave.com /etc/default/brave-browser /etc/sysctl.d/30-brave.conf 2>/dev/null')\" ]"
chk "browser: Mozilla source (Signed-By keyring present) + origin pin 1000" "R 'grep -q ^URIs:.https://packages.mozilla.org/apt /etc/apt/sources.list.d/mozilla.sources && grep -q ^Signed-By:./usr/share/keyrings/packages.mozilla.org.gpg /etc/apt/sources.list.d/mozilla.sources && test -s /usr/share/keyrings/packages.mozilla.org.gpg && grep -q \"^Pin: origin packages.mozilla.org\" /etc/apt/preferences.d/mozilla && grep -q ^Pin-Priority:.1000 /etc/apt/preferences.d/mozilla'"
chk "browser: Brave source, keyring and defaults file absent" "[ -z \"\$(R 'ls /etc/apt/sources.list.d/brave-browser-release.sources /usr/share/keyrings/brave-browser-archive-keyring.gpg /etc/default/brave-browser 2>/dev/null')\" ]"
chk "browser: only ubuntu + mozilla + fabos sources; no vendor key in trusted.gpg.d" "[ -z \"\$(R 'ls /etc/apt/sources.list.d | grep -v -E \"^(ubuntu|mozilla|fabos)\\.sources\"; ls /etc/apt/trusted.gpg.d/ | grep -i -E \"brave|mozilla|google\"')\" ]"
chk "browser: Firefox is the default (mimeapps.list)"    "R 'grep -q ^x-scheme-handler/https=firefox.desktop /etc/xdg/mimeapps.list && grep -q ^x-scheme-handler/http=firefox.desktop /etc/xdg/mimeapps.list && grep -q ^text/html=firefox.desktop /etc/xdg/mimeapps.list && test -f /usr/share/applications/firefox.desktop'"
chk "browser: firefox NOT in 00-fabos-blocklist (it would pin Mozilla's build out too); no Brave desktop file" "! R 'grep -qw firefox /etc/apt/preferences.d/00-fabos-blocklist' && [ -z \"\$(R 'ls /usr/share/applications/brave-browser.desktop /usr/share/applications/com.brave.Browser.desktop 2>/dev/null')\" ]"

# Top bar quick settings + dock (2026-09-15): two Fab OS plasmoids replace the four stock tray icons and icontasks; the
# tray keeps only third-party icons; one bar size drives the indicators and the clock; Firefox is the pinned browser again
# (second pass, below).
QS=/usr/share/plasma/plasmoids/in.patienceai.fabos.quicksettings
DK=/usr/share/plasma/plasmoids/in.patienceai.fabos.dock
chk "quick settings + dock plasmoids installed, Authors Patience AI" "R 'test -f $QS/metadata.json && test -f $DK/metadata.json && grep -q \"\\\"Name\\\": \\\"Patience AI\\\"\" $QS/metadata.json && grep -q \"\\\"Name\\\": \\\"Patience AI\\\"\" $DK/metadata.json && grep -q \"\\\"Id\\\": \\\"in.patienceai.fabos.quicksettings\\\"\" $QS/metadata.json && grep -q \"\\\"Id\\\": \\\"in.patienceai.fabos.dock\\\"\" $DK/metadata.json'"
chk "both applets ship main.qml + config schema + settings page" "R 'test -f $QS/contents/ui/main.qml && test -f $QS/contents/config/main.xml && test -f $QS/contents/config/config.qml && test -f $QS/contents/ui/configGeneral.qml && test -f $QS/contents/code/status.sh && test -f $DK/contents/ui/main.qml && test -f $DK/contents/ui/TaskItem.qml && test -f $DK/contents/config/main.xml && test -f $DK/contents/ui/configGeneral.qml'"
chk "layout: top bar holds quick settings, dock replaces icontasks" "R 'grep -q \"top.addWidget(\\\"in.patienceai.fabos.quicksettings\\\")\" $LAYOUT && grep -q \"dock.addWidget(\\\"in.patienceai.fabos.dock\\\")\" $LAYOUT' && [ -z \"\$(R 'grep \"addWidget(\\\"org.kde.plasma.icontasks\\\")\" $LAYOUT')\" ]"
chk "layout: Firefox is the pinned browser again, Brave nowhere" "R 'grep -q applications:firefox.desktop $LAYOUT' && ! R 'grep -ci brave $LAYOUT' | grep -qE '^[1-9]'"
chk "layout: one bar size drives quick settings + clock (Inter 12 / 13 / 15)" "R 'grep -q \"^var BAR_SIZE = \" $LAYOUT && grep -q \"Inter 12 / 13 / 15\" $LAYOUT && grep -q \"quick.writeConfig(\\\"barSize\\\", BAR_SIZE)\" $LAYOUT && grep -q \"clock.writeConfig(\\\"barSize\\\", BAR_SIZE)\" $LAYOUT && grep -q \"tasks.writeConfig(\\\"magnify\\\", MAGNIFY)\" $LAYOUT'"
chk "system tray hides the five duplicated stock icons" "R 'grep -q \"\\\"hiddenItems\\\", \\[\" /usr/lib/fabos/tray-defaults.js && grep hiddenItems /usr/lib/fabos/tray-defaults.js | grep -q org.kde.plasma.battery && grep hiddenItems /usr/lib/fabos/tray-defaults.js | grep -q org.kde.plasma.networkmanagement && grep hiddenItems /usr/lib/fabos/tray-defaults.js | grep -q org.kde.plasma.volume && grep hiddenItems /usr/lib/fabos/tray-defaults.js | grep -q org.kde.plasma.bluetooth && grep hiddenItems /usr/lib/fabos/tray-defaults.js | grep -q org.kde.plasma.notifications && grep -q \"\\\"shownItems\\\", \\[\\]\" /usr/lib/fabos/tray-defaults.js && grep -q tray-defaults-done-v2 /usr/lib/fabos/tray-defaults'"
chk "quick settings: battery percentage beside the glyph in the clock size" "R 'grep -q \"root.st.batPct + \\\"%\\\"\" $QS/contents/ui/main.qml && grep -q \"textPx: root.clockPx\" $QS/contents/ui/main.qml && grep -q \"function clockSizeFor\" $QS/contents/ui/status.js'"
chk "quick settings: slide-down pane, speed text, dnd, stock applets via plasmawindowed" "R 'grep -q -E \"duration: 220; easing.type: Easing.OutCubic\" $QS/contents/ui/main.qml && grep -q \"function speedText\" $QS/contents/ui/status.js && grep -q toggleDnd $QS/contents/ui/main.qml && grep -q \"plasmawindowed org.kde.plasma.networkmanagement\" $QS/contents/ui/main.qml && grep -q \"plasmawindowed org.kde.plasma.volume\" $QS/contents/ui/main.qml && grep -q \"plasmawindowed org.kde.plasma.battery\" $QS/contents/ui/main.qml && grep -q \"plasmawindowed org.kde.plasma.bluetooth\" $QS/contents/ui/main.qml'"
chk "quick settings: every wired CLI exists in the image" "R 'command -v nmcli && command -v bluetoothctl && command -v wpctl && command -v upower && command -v powerprofilesctl && command -v plasmawindowed && command -v kcmshell6 && command -v qdbus6 && command -v systemsettings' >/dev/null"
chk "dock: TasksModel backend, magnify 1.6/1.3/1.1, Firefox default launcher" "R 'grep -q \"import org.kde.taskmanager as TaskManager\" $DK/contents/ui/main.qml && grep -q \"TaskManager.TasksModel\" $DK/contents/ui/main.qml && grep -q \"1.6\" $DK/contents/ui/main.qml && grep -q \"1.3\" $DK/contents/ui/main.qml && grep -q \"1.1\" $DK/contents/ui/main.qml && grep -q applications:firefox.desktop $DK/contents/config/main.xml && grep -q \"name=\\\"magnify\\\"\" $DK/contents/config/main.xml'"
chk "dock + quick settings share the magnify setting via the shell scripting API; the size goes to the Fab OS clock" "R 'grep -q \"in.patienceai.fabos.dock\" $QS/contents/ui/status.js && grep -q evaluateScript $QS/contents/ui/status.js && grep -q \"in.patienceai.fabos.clock\" $QS/contents/ui/status.js' && [ -z \"\$(R 'grep org.kde.plasma.digitalclock $QS/contents/ui/status.js')\" ]"
chk "desktop applets carry no hard-coded colours" "! R 'grep -nE \"color: \\\"#|color: \\\"(white|black|red|blue)\\\"\" $QS/contents/ui/*.qml $DK/contents/ui/*.qml' | grep -q ."
# Review fixes (2026-09-15, source tree): the notification cross is reachable (whole-row hover area + the button's own
# hover), the bar magnifies the glyph only, the dock's applet width does not follow a hover, one owner per shared setting.
QSS=$SRC/packages/fabos-desktop/usr/share/plasma/plasmoids/in.patienceai.fabos.quicksettings/contents
DKS=$SRC/packages/fabos-desktop/usr/share/plasma/plasmoids/in.patienceai.fabos.dock/contents
chk "notification row: dismiss cross reachable (no dead strip, button hover counts)" "grep -q 'readonly property bool hovered: ma.containsMouse' $QSS/ui/SmallButton.qml && grep -q 'rowArea.containsMouse || dismissBtn.hovered' $QSS/ui/NotificationRow.qml && ! grep -q 'rightMargin: 36' $QSS/ui/NotificationRow.qml && grep -q 'history: notifList.model' $QSS/ui/main.qml"
chk "bar indicators magnify the glyph only; pane visibility imperative" "grep -c 'scale: hover.hovered' $QSS/ui/Indicator.qml | grep -qx 1 && ! grep -qE '^    scale: hover.hovered' $QSS/ui/Indicator.qml && grep -q 'ReleaseWithinBounds' $QSS/ui/Indicator.qml && ! grep -q 'visible: root.paneMode !== \"closed\"' $QSS/ui/main.qml"
chk "dock: applet width constant on hover (resting + reserve), magnify write-back" "grep -q 'Layout.preferredWidth: dock.appletWidth' $DKS/ui/main.qml && grep -q 'readonly property int reserve' $DKS/ui/main.qml && grep -q 'in.patienceai.fabos.quicksettings' $DKS/ui/main.qml && grep -q evaluateScript $DKS/ui/main.qml"
chk "one owner per shared setting: bar size + magnify switch in quick settings, strength in the dock" "! grep -q 'name=\"magnification\"' $QSS/config/main.xml && ! grep -q 'writeConfig(\\\\\"magnification' $QSS/ui/status.js && ! grep -q cfg_magnification $QSS/ui/configGeneral.qml && grep -q 'name=\"magnification\"' $DKS/config/main.xml && ! grep -q 'quick.writeConfig(\"magnification\"' $SRC/packages/fabos-desktop/usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/layouts/org.kde.plasma.desktop-layout.js"
chk "applet harness renders both Fab OS schemes with the kde platform theme + a real pointer" "grep -q 'QT_QPA_PLATFORMTHEME=kde' $SRC/tests/desktop-applets-qml-test.sh && grep -q FabDark $SRC/tests/desktop-applets-qml-test.sh && grep -q FabLight $SRC/tests/desktop-applets-qml-test.sh && test -f $SRC/tests/quicksettings-qml-harness/fakeinput.py && grep -q org_kde_kwin_fake_input $SRC/tests/dock-qml-harness/kwin-session.sh"
# Smooth desktop round (2026-09-15): half-length animations, no tearing, blur off under 3.5 GB via the login tune, File
# Search runner off, voice listener at background priority, the ask bar's single-curl snapshot, the two-process light probe.
chk "kdeglobals: AnimationDurationFactor=0.5 (verified key: kwin.kcfg [KDE])" "R 'grep -q ^AnimationDurationFactor=0.5$ /etc/xdg/kdeglobals'"
chk "kwinrc: [Compositing] AllowTearing=false; LatencyPolicy (gone from KWin 6.6) not set" "R 'grep -A3 \"^\\[Compositing\\]\" /etc/xdg/kwinrc | grep -q ^AllowTearing=false && ! grep -q ^LatencyPolicy= /etc/xdg/kwinrc && ! grep -q LatencyPolicy /usr/share/config.kcfg/kwin.kcfg'"
chk "low-RAM login tune shipped (.sh so build-debs keeps it 0755) and hooked via sh before KWin starts" "R 'test -x /usr/lib/fabos/lowram-tune.sh && grep -qF \"sh /usr/lib/fabos/lowram-tune.sh\" /etc/xdg/plasma-workspace/env/40-fabos-lowram.sh && ! grep -qF -- \"-x /usr/lib/fabos/lowram-tune\" /etc/xdg/plasma-workspace/env/40-fabos-lowram.sh && grep -q blurEnabled /usr/lib/fabos/lowram-tune.sh && grep -q 3500000 /usr/lib/fabos/lowram-tune.sh'"
chk "krunnerrc: File Search (baloosearch, a D-Bus-activated runner) off by default" "R 'grep -q ^baloosearchEnabled=false /etc/xdg/krunnerrc && grep -q X-KDE-PluginInfo-Name=baloosearch /usr/share/krunner/dbusplugins/plasma-runner-baloosearch.desktop'"
chk "fabos-voiced unit: Nice=15 + IOSchedulingClass=idle" "R 'grep -q ^Nice=15$ /usr/lib/systemd/user/fabos-voiced.service && grep -q ^IOSchedulingClass=idle$ /usr/lib/systemd/user/fabos-voiced.service'"
chk "ask bar polls with one curl snapshot (status + task), read builtins, no cat" "R 'grep -q \"function snapshotCommand\" /usr/share/plasma/plasmoids/in.patienceai.fabos.askbar/contents/ui/agent.js && grep -q \"snapTimer\" /usr/share/plasma/plasmoids/in.patienceai.fabos.askbar/contents/ui/main.qml && ! grep -q \"trailingPoll1\" /usr/share/plasma/plasmoids/in.patienceai.fabos.askbar/contents/ui/main.qml'"
chk "quick settings probe prints one JSON line, has a --light mode (2 processes), reads BlueZ + power profile over busctl" "R 'grep -q -- \"--light\" $QS/contents/code/status.sh && grep -q \"exec awk\" $QS/contents/code/status.sh && grep -q \"get-property org.bluez\" $QS/contents/code/status.sh && grep -q net.hadess.PowerProfiles $QS/contents/code/status.sh && ! grep -qE \"^[^#]*[$][(](powerprofilesctl|bluetoothctl)\" $QS/contents/code/status.sh && grep -q lightCmd $QS/contents/ui/main.qml'"
chk "Fab AI Controls: daemon calls on a worker thread (ApiQueue), no synchronous api() in the main window" "R 'grep -q \"class ApiQueue(QThread)\" /usr/lib/fabos/agent/command_center.py && grep -q \"def flush_api\" /usr/lib/fabos/agent/command_center.py && grep -q POLL_THREAD_HIDDEN_MS /usr/lib/fabos/agent/command_center.py'"
chk "dock: no endless startup pulse" "! R 'grep -q \"loops: Animation.Infinite\" $DK/contents/ui/TaskItem.qml'"
# Enterprise security (ADR-0017, 2026-09-15) — the controls tests/security-check.sh inspects in depth; asserted here too so one run sees them.
chk "security: no NOPASSWD sudoers rule for the agent (root via pkexec + polkit)" "! R 'test -e /etc/sudoers.d/fabos-agent' && ! R 'grep -rE \"NOPASSWD.*rootexec\" /etc/sudoers /etc/sudoers.d 2>/dev/null' | grep -q . && R 'test -f /usr/share/polkit-1/actions/in.patienceai.fabos.rootexec.policy && grep -q auth_admin_keep /usr/share/polkit-1/actions/in.patienceai.fabos.rootexec.policy'"
chk "security: sysctl hardening file + three Fab OS AppArmor profiles parse"    "R 'test -f /etc/sysctl.d/70-fabos-hardening.conf && apparmor_parser -Q -K /etc/apparmor.d/fabos-agentd /etc/apparmor.d/fabos-voiced /etc/apparmor.d/fabos-llama 2>/dev/null'"
chk "security: avahi off, unattended-upgrades on, 10-min lock, lid sleeps"       "R 'test \"\$(systemctl is-enabled avahi-daemon.service 2>/dev/null)\" = disabled && systemctl is-enabled unattended-upgrades >/dev/null && grep -q ^Timeout=10 /etc/xdg/kscreenlockerrc && grep -q ^LidAction=1 /etc/xdg/powerdevilrc'"
chk "security: bubblewrap present; run_shell sandbox + policy loader + audit chain in the daemon" "R 'test -x /usr/bin/bwrap && grep -q \"def sandbox_argv\" /usr/lib/fabos/agent/fabos_agentd.py && grep -q \"class Policy\" /usr/lib/fabos/agent/fabos_agentd.py && grep -q \"def audit_hmac\" /usr/lib/fabos/agent/fabos_agentd.py'"
chk "security: no marketing words in the enterprise docs"                        "! grep -qiE 'military[- ]grade|bank[- ]grade|unhackable|bulletproof|100% secure' $SRC/docs/ENTERPRISE.md $SRC/SECURITY.md $SRC/docs/decisions/ADR-0017-enterprise-security.md"
# Enterprise security review round (ADR-0017 amendment 7-12): environment allowlist, agent-socket masking, honest release signing
chk "security: children get an allowlisted environment, never the daemon's (no provider key reaches run_shell)" "grep -q 'def clean_env' $SRC/packages/fabos-agent/usr/lib/fabos/agent/fabos_agentd.py && grep -q 'def tool_env' $SRC/packages/fabos-agent/usr/lib/fabos/agent/fabos_agentd.py && ! grep -q 'env = dict(os.environ)' $SRC/packages/fabos-agent/usr/lib/fabos/agent/fabos_agentd.py && grep -q 'LEAKTEST' $SRC/tests/agent-test.py"
chk "security: sandbox masks the ssh/gpg agent sockets in the runtime dir; fabos-voiced complain with the missing helpers listed" "grep -q 'def sandbox_masked' $SRC/packages/fabos-agent/usr/lib/fabos/agent/fabos_agentd.py && grep -q 'flags=(complain' $SRC/packages/fabos-voice/etc/apparmor.d/fabos-voiced && grep -q wpctl $SRC/packages/fabos-voice/etc/apparmor.d/fabos-voiced && grep -q gnutrue $SRC/packages/fabos-voice/etc/apparmor.d/fabos-voiced"
chk "security: release checksums signed by a script that exists; docs name the polkit cache window and the ISO signature gap" "test -x $SRC/scripts/release-checksums.sh && grep -q release-checksums.sh $SRC/scripts/publish-iso.sh && grep -q release-checksums.sh $SRC/scripts/release-github.sh && grep -q 'AUTH_ADMIN' $SRC/docs/ENTERPRISE.md && grep -q 'not signed' $SRC/docs/ENTERPRISE.md && grep -q 'def sudo_path_allowed' $SRC/packages/fabos-agent/usr/lib/fabos/agent/rootexec"
# Rounded corners on every window (ADR-0019, 2026-09-15): the KDE-Rounded-Corners KWin effect, built from source inside the image
# (image/rounded-corners-build.sh -> package fabos-rounded-corners), enabled in kwinrc at radius 14 = the Aurorae frame's top radius.
RC_SO=/usr/lib/x86_64-linux-gnu/qt6/plugins/kwin/effects/plugins/kwin4_effect_shapecorners.so
chk "rounded corners: effect plugin, its KCM and both shaders installed" "R 'test -f $RC_SO && test -f /usr/lib/x86_64-linux-gnu/qt6/plugins/kwin/effects/configs/kwin_shapecorners_config.so && test -f /usr/share/kwin/shaders/shapecorners.frag && test -f /usr/share/kwin/shaders/shapecorners_core.frag'"
chk "rounded corners: plugin metadata says KWin/Effect + KCM kwin_shapecorners_config (id = file name)" "R 'grep -a -q KWin/Effect $RC_SO && grep -a -q X-KDE-ConfigModule $RC_SO && grep -a -q kwin_shapecorners_config $RC_SO'"
chk "rounded corners: package fabos-rounded-corners installed, in the manifest, owns the plugin; GPL-3.0 copyright names the pinned tarball" "R 'dpkg -s fabos-rounded-corners' | grep -q '^Status: install ok installed' && R 'grep -q ^fabos-rounded-corners /usr/share/fabos/manifest.txt && dpkg -S $RC_SO | grep -q ^fabos-rounded-corners: && grep -q GPL-3.0 /usr/share/doc/fabos-rounded-corners/copyright && grep -q f3f03d96e17ae4b7dcee6347a01c75de6f90ed19e070e98ae8bf2dd71ae276db /usr/share/doc/fabos-rounded-corners/copyright && test -s /usr/share/doc/fabos-rounded-corners/LICENSE'"
chk "rounded corners: no build tools left behind (kwin-dev, cmake, g++, extra-cmake-modules)" "! R 'dpkg -s kwin-dev 2>/dev/null; dpkg -s cmake 2>/dev/null; dpkg -s g++ 2>/dev/null; dpkg -s extra-cmake-modules 2>/dev/null' | grep -q '^Status: install ok installed'"
chk "kwinrc: effect enabled; [Round-Corners] radius 14 active + inactive, circular, 1 px outline, square when maximised / tiled / full-screen" "R 'grep -q ^kwin4_effect_shapecornersEnabled=true /etc/xdg/kwinrc && grep -q \"^\\[Round-Corners\\]\" /etc/xdg/kwinrc && grep -q ^Size=14$ /etc/xdg/kwinrc && grep -q ^InactiveCornerRadius=14$ /etc/xdg/kwinrc && grep -q ^UseSquircleShape=false /etc/xdg/kwinrc && grep -q ^OutlineThickness=1$ /etc/xdg/kwinrc && grep -q ^DisableRoundMaximize=true /etc/xdg/kwinrc && grep -q ^DisableRoundTile=true /etc/xdg/kwinrc && grep -q ^DisableRoundFullScreen=true /etc/xdg/kwinrc'"
chk "decoration: Aurorae top arcs are radius 14 = the effect's Size — arc ends 42 28 / 64 42 (padding 28) OR 46 32 / 68 46 (padding 32); generator + probe P 28 or 32" "R 'grep -q -e \"A14 14 0 0 1 42 28\" -e \"A14 14 0 0 1 46 32\" /usr/share/aurorae/themes/FabOS/decoration.svg && grep -q -e \"A14 14 0 0 1 64 42\" -e \"A14 14 0 0 1 68 46\" /usr/share/aurorae/themes/FabOS/decoration.svg' && grep -q -E '^P, R, TH = (28|32), 14, 36' $SRC/brand/gen/aurorae_theme.py && grep -q -E '^P, R, W, H = (28|32), 14, 400, 300' $SRC/tests/decoration-render-harness/probe.py"   # 2026-09-16 (ADR-0019 amendment): padding 28 -> 32 moves the arc end points (42/64 -> 46/68); both geometries accepted here, the strict padding-32 assertion is the appended "one shadow: padding 32" check
chk "rounded corners: legal + docs + VM test (GPL-3.0 text, attribution, THIRD-PARTY row, source offer with URL + sha, ADR-0019, corners-vm.sh)" "test -s $SRC/THIRD_PARTY_LICENSES/GPL-3.0.txt && grep -q KDE-Rounded-Corners $SRC/ATTRIBUTIONS.md && grep -q KDE-Rounded-Corners $SRC/legal/THIRD-PARTY.md && grep -q KDE-Rounded-Corners/archive/refs/tags/v0.10.0.tar.gz $SRC/legal/SOURCE-OFFER.md && grep -q f3f03d96e17ae4b7dcee6347a01c75de6f90ed19e070e98ae8bf2dd71ae276db $SRC/legal/SOURCE-OFFER.md && grep -q f3f03d96e17ae4b7dcee6347a01c75de6f90ed19e070e98ae8bf2dd71ae276db $SRC/image/rounded-corners-build.sh && test -f $SRC/docs/decisions/ADR-0019-rounded-corners-effect.md && test -x $SRC/tests/corners-vm.sh && grep -q loadedEffects $SRC/tests/corners-vm.sh"
# Firefox is back (2026-09-15, ADR-0018): Mozilla's build from packages.mozilla.org, Mozilla's enterprise-policy file for a quiet first
# run (no tour, no telemetry/studies, no default-browser nag, no stock bookmarks, home page = HOME_URL, nothing locked), Ubuntu's
# `firefox` AppArmor profile so the content sandbox gets user namespaces. Image items pass only on an image rebuilt from this tree.
chk "browser: policies.json valid JSON with the quiet-first-run keys (incl. SkipTermsOfUse), nothing locked; Mozilla's distribution.ini untouched" "R 'python3 -m json.tool /usr/lib/firefox/distribution/policies.json >/dev/null && grep -q \"\\\"DisableTelemetry\\\": true\" /usr/lib/firefox/distribution/policies.json && grep -q \"\\\"SkipTermsOfUse\\\": true\" /usr/lib/firefox/distribution/policies.json && grep -q \"\\\"DontCheckDefaultBrowser\\\": true\" /usr/lib/firefox/distribution/policies.json && grep -q \"\\\"NoDefaultBookmarks\\\": true\" /usr/lib/firefox/distribution/policies.json && grep -q \"\\\"OverrideFirstRunPage\\\": \\\"\\\"\" /usr/lib/firefox/distribution/policies.json && grep -q \"\\\"URL\\\": \\\"https://fabos.patienceai.in\" /usr/lib/firefox/distribution/policies.json && ! grep -q \"\\\"Locked\\\": true\" /usr/lib/firefox/distribution/policies.json && grep -q ^id=mozilla-deb /usr/lib/firefox/distribution/distribution.ini'"
chk "browser: Ubuntu's firefox AppArmor profile (userns for the content sandbox) present and parses" "R 'test -f /etc/apparmor.d/firefox && grep -q userns /etc/apparmor.d/firefox && apparmor_parser -Q -K /etc/apparmor.d/firefox'"
chk "browser (source tree): Mozilla source + pin 1000 in fabos-branding, firefox.desktop default, policies.json valid, no brave ids" "test -f $SRC/packages/fabos-branding/etc/apt/sources.list.d/mozilla.sources && grep -q '^Pin-Priority: 1000' $SRC/packages/fabos-branding/etc/apt/preferences.d/mozilla && grep -q '^x-scheme-handler/https=firefox.desktop' $SRC/packages/fabos-desktop/etc/xdg/mimeapps.list && python3 -m json.tool $SRC/packages/fabos-desktop/usr/lib/firefox/distribution/policies.json >/dev/null && ! grep -qiE 'brave-browser|brave\.com|brave-keyring' $SRC/packages/fabos-desktop/etc/xdg/mimeapps.list $SRC/packages/fabos-desktop-meta/DEBIAN/control $SRC/packages/fabos-branding/etc/apt/sources.list.d/mozilla.sources $SRC/packages/fabos-desktop/usr/lib/firefox/distribution/policies.json $SRC/tests/security/suid-baseline.txt"
# Upgrade path for a system installed from the 1.0-3 / 1.0-4 images (ADR-0018): fabos-desktop-meta Recommends `firefox` alone (the old
# `| www-browser` alternative was satisfied by brave-browser, which Provides www-browser, so Firefox never arrived), and fabos-desktop
# ships the one-shot fabos-browser-migrate.service: its postinst flags the job when brave-browser, Brave's source, `firefox` in the
# image-written 00-fabos-blocklist (a `Package:` pin there hits Mozilla's build too) or a non-Mozilla firefox is found; the job un-pins
# firefox, installs Mozilla's build, purges the old browser, repoints stale per-user pins. The image item passes only on a rebuilt image.
chk "browser (upgrade, image): fabos-browser-migrate.service + script shipped, unit verifies, MemoryHigh set, gated on the pending flag, flag absent" "R 'test -x /usr/lib/fabos/browser-migrate.sh && sh -n /usr/lib/fabos/browser-migrate.sh && grep -q ^ConditionPathExists=/var/lib/fabos/browser-migrate-pending /usr/lib/systemd/system/fabos-browser-migrate.service && grep -q ^MemoryHigh= /usr/lib/systemd/system/fabos-browser-migrate.service && systemd-analyze verify /usr/lib/systemd/system/fabos-browser-migrate.service && test ! -e /var/lib/fabos/browser-migrate-pending'"
chk "browser (upgrade, source tree): meta Recommends firefox alone, postinst flags the migration, script un-pins firefox + purges the old browser, Driver.qml fixture pins firefox.desktop" "grep -qE '^Recommends: .*, firefox\$' $SRC/packages/fabos-desktop-meta/DEBIAN/control && grep -q browser-migrate-pending $SRC/packages/fabos-desktop/DEBIAN/postinst && grep -q fabos-browser-migrate.service $SRC/packages/fabos-desktop/DEBIAN/postinst && sh -n $SRC/packages/fabos-desktop/usr/lib/fabos/browser-migrate.sh && grep -q 00-fabos-blocklist $SRC/packages/fabos-desktop/usr/lib/fabos/browser-migrate.sh && grep -q 'purge brave-browser brave-keyring' $SRC/packages/fabos-desktop/usr/lib/fabos/browser-migrate.sh && grep -q '\"SkipTermsOfUse\": true' $SRC/packages/fabos-desktop/usr/lib/firefox/distribution/policies.json && grep -q applications:firefox.desktop $SRC/tests/dock-qml-harness/Driver.qml && ! grep -qi brave $SRC/tests/dock-qml-harness/Driver.qml"
# Top bar & dock, second pass from the owner's device test (2026-09-15): the tray's extraItems built without the five
# replaced applets (hiddenItems only folds them into the popup), a Fab OS clock applet instead of the stock digital
# clock (one size for everything in the bar), the rate always on while a link is up, customisable tiles (tilesJson),
# the no-blink slide-down (transparent dialog at its final size, the card animates), Wi-Fi from nmcli's own signal,
# uniform dock tiles (start + peek drawn by the dock at tileScale), the bigger notification pane, Firefox back.
CKS=$SRC/packages/fabos-desktop/usr/share/plasma/plasmoids/in.patienceai.fabos.clock
LAYS=$SRC/packages/fabos-desktop/usr/share/plasma/look-and-feel/in.patienceai.fabos.desktop/contents/layouts/org.kde.plasma.desktop-layout.js
chk "layout: tray extraItems without network/bluetooth/volume/battery/brightness, knownItems keeps them (configureTray)" "grep -qF 'var TRAY_REPLACED = [\"org.kde.plasma.networkmanagement\", \"org.kde.plasma.bluetooth\", \"org.kde.plasma.volume\", \"org.kde.plasma.battery\", \"org.kde.plasma.brightness\"]' $LAYS && grep -qF 'tray.writeConfig(\"extraItems\", without(extra, TRAY_REPLACED))' $LAYS && grep -qF 'known = union(union(known, extra), TRAY_REPLACED)' $LAYS && grep -qF 'configureTray(tray)' $LAYS && grep -qF 'tray.writeConfig(\"hiddenItems\", TRAY_HIDDEN)' $LAYS"
chk "layout: Fab OS clock applet in the top bar, stock digital clock absent; the applet ships Inter 700" "grep -qF 'top.addWidget(\"in.patienceai.fabos.clock\")' $LAYS && ! grep -q 'org.kde.plasma.digitalclock' $LAYS && test -f $CKS/metadata.json && grep -qF '\"Id\": \"in.patienceai.fabos.clock\"' $CKS/metadata.json && grep -qF 'font.family: \"Inter\"' $CKS/contents/ui/main.qml && grep -qF 'font.weight: Font.Bold' $CKS/contents/ui/main.qml && grep -qF 'X-Plasma-Provides\": [\"org.kde.plasma.time\"' $CKS/metadata.json"
chk "clock: one px table with the indicators (12/13/15 from barSize), pushed from the quick settings' page via the shell scripting API" "grep -qF 'readonly property int px: barSize === \"small\" ? 12 : (barSize === \"large\" ? 15 : 13)' $CKS/contents/ui/main.qml && grep -qF 'function clockSizeFor(barSize) { return barSize === \"small\" ? 12 : (barSize === \"large\" ? 15 : 13) }' $QSS/ui/status.js && grep -qF 'widgets(\\\"in.patienceai.fabos.clock\\\")' $QSS/ui/status.js && ! grep -q digitalclock $QSS/ui/status.js"
chk "quick settings: speed always on while a link is up (0 kB/s floor, no idle hide; layout writes showSpeed=true)" "grep -qF 'readonly property bool speedVisible: Plasmoid.configuration.showSpeed && st.iface !== \"\"' $QSS/ui/main.qml && ! grep -q zeroSamples $QSS/ui/main.qml && grep -qF 'if (bps < 1000) return (bps < 50 ? \"0\" : (bps / 1000).toFixed(1)) + \" kB/s\"' $QSS/ui/status.js && grep -qF 'quick.writeConfig(\"showSpeed\", true)' $LAYS"
chk "quick settings: tiles model (tilesJson default with the 12 ids, Tiles config page, edit mode with drag / size / remove / reset)" "grep -qF 'name=\"tilesJson\"' $QSS/config/main.xml && grep -qF '<default>[{\"id\":\"wifi\"' $QSS/config/main.xml && grep -q nightlight $QSS/config/main.xml && grep -q screenshot $QSS/config/main.xml && test -f $QSS/ui/configTiles.qml && grep -q DragHandler $QSS/ui/main.qml && grep -qF 'Status.moveTileTo(' $QSS/ui/main.qml && grep -qF 'Status.toggleTileSize(' $QSS/ui/main.qml && grep -qF 'root.saveTiles(Status.defaultTiles())' $QSS/ui/main.qml"
chk "quick settings: no-blink pane (transparent dialog at its final size; the CARD animates y + opacity, 220 ms; radius 24 bottom corners)" "grep -qF 'backgroundHints: PlasmaCore.Dialog.NoBackground' $QSS/ui/main.qml && grep -qF 'y: Math.round(-height * (1 - pane.openProgress))' $QSS/ui/main.qml && grep -qF 'opacity: pane.openProgress' $QSS/ui/main.qml && grep -qF 'duration: 220; easing.type: Easing.OutCubic' $QSS/ui/main.qml && grep -qF 'bottomLeftRadius: pane.radius; bottomRightRadius: pane.radius' $QSS/ui/main.qml && ! grep -q 'Behavior on paneHeight' $QSS/ui/main.qml"
chk "quick settings: Wi-Fi from nmcli ACTIVE,SIGNAL (five glyphs at 80/55/30/5), wired and radio-off glyphs, never /proc/net/wireless first" "grep -qF 'nmcli -w 2 -t -f ACTIVE,SIGNAL dev wifi list --rescan no' $QSS/code/status.sh && grep -qF 'nmcli -w 3 -t -f DEVICE,TYPE,STATE,CONNECTION dev status' $QSS/code/status.sh && grep -qF 'signal >= 80 ? \"excellent\" : signal >= 55 ? \"good\" : signal >= 30 ? \"ok\" : signal >= 5 ? \"weak\" : \"none\"' $QSS/ui/status.js && grep -qF 'return \"network-wired\"' $QSS/ui/status.js && grep -qF 'return \"network-wireless-off\"' $QSS/ui/status.js"
chk "notification pane: 28 gridUnits, 56 px rows, 32 px app icon, 13 px body, Clear all, 60 % screen cap" "grep -qF 'Kirigami.Units.gridUnit * 28' $QSS/ui/main.qml && grep -qF 'implicitHeight: Math.max(56, content.implicitHeight + 14)' $QSS/ui/NotificationRow.qml && grep -qF 'Layout.preferredWidth: 32; Layout.preferredHeight: 32' $QSS/ui/NotificationRow.qml && grep -qF 'text: \"Clear all\"' $QSS/ui/main.qml && grep -qF 'Math.round(root.screenH * 0.6)' $QSS/ui/main.qml"
chk "dock: one size for everything (start + peek are row items, every tile at tileScale), Firefox pinned, Brave gone, launcher zero-width" "grep -qF 'name=\"showStart\"' $DKS/config/main.xml && grep -qF 'name=\"tileScale\"' $DKS/config/main.xml && ! grep -q symbolScale $DKS/config/main.xml && grep -qF 'icon: \"start-here\"' $DKS/ui/main.qml && grep -qF 'tileBackground: true' $DKS/ui/main.qml && grep -q applications:firefox.desktop $DKS/config/main.xml && ! grep -qi brave $DKS/config/main.xml && grep -qF 'kickoff.writeConfig(\"icon\", \"\")' $LAYS && grep -qF 'kickoff.writeConfig(\"menuLabel\", \"\")' $LAYS"
chk "desktop applets test covers the clock, the dock icon-extent measurement and the real-plasmashell tray proof" "grep -q clock-qml-harness $SRC/tests/desktop-applets-qml-test.sh && grep -q measure.py $SRC/tests/desktop-applets-qml-test.sh && grep -qF 'want tray && tray' $SRC/tests/desktop-applets-qml-test.sh && test -f $SRC/tests/dock-qml-harness/measure.py && test -f $SRC/tests/clock-qml-harness/Driver.qml && grep -q analyseSamples $SRC/tests/quicksettings-qml-harness/Driver.qml"
# One shadow source (2026-09-16, ADR-0019 amendment): the KDE-Rounded-Corners effect draws the only window shadow
# (UseNativeDecorationShadows=false); the Aurorae frame is flat — padding 32 with an alpha-1/255 carrier, no gradient/mask/filter.
# These read the SOURCE tree (they hold before the image is rebuilt); the image-side decoration checks above accept both frames.
DECO=$SRC/packages/fabos-desktop/usr/share/aurorae/themes/FabOS; DECOL=$SRC/packages/fabos-desktop/usr/share/aurorae/themes/FabOSLight
KWRC=$SRC/packages/fabos-desktop/etc/xdg/kwinrc
chk "one shadow: kwinrc [Round-Corners] UseNativeDecorationShadows=false, ShadowSize=40, InactiveShadowSize=36, black 128/64, palette shadow off (QPalette::Shadow is accent-tinted), *ShadowUseCustom=true (KCM radio)" "grep -q '^UseNativeDecorationShadows=false$' $KWRC && grep -q '^ShadowSize=40$' $KWRC && grep -q '^InactiveShadowSize=36$' $KWRC && grep -q '^ActiveShadowUseCustom=true$' $KWRC && grep -q '^InactiveShadowUseCustom=true$' $KWRC && grep -q '^ShadowColor=0,0,0$' $KWRC && grep -q '^InactiveShadowColor=0,0,0$' $KWRC && grep -q '^ActiveShadowAlpha=128$' $KWRC && grep -q '^InactiveShadowAlpha=64$' $KWRC && grep -q '^ActiveShadowUsePalette=false$' $KWRC && grep -q '^InactiveShadowUsePalette=false$' $KWRC && grep -q '^BorderSize=None$' $KWRC && grep -q '^BorderSizeAuto=false$' $KWRC"
chk "one shadow: decoration.svg is flat — no linearGradient/radialGradient/<mask>/<filter>/url(#)/stop-color; 16 carrier rects at fill-opacity 0.004; desc names the effect and the notch" "! grep -q -E 'linearGradient|radialGradient|<mask|<filter|url\(#|stop-color' $DECO/decoration.svg && [ \$(grep -o 'fill-opacity:0.004' $DECO/decoration.svg | wc -l) -eq 16 ] && grep -q UseNativeDecorationShadows=false $DECO/decoration.svg && grep -q notch $DECO/decoration.svg && ! grep -q 'id=\"mask-' $DECO/decoration.svg"
chk "one shadow: padding 32 on all sides in FabOSrc + FabOSLightrc, borders 0, arcs end at 46 32 / 68 46 (radius 14), generator P=32 + CARRIER, probe P=32" "grep -q '^PaddingLeft=32$' $DECO/FabOSrc && grep -q '^PaddingRight=32$' $DECO/FabOSrc && grep -q '^PaddingTop=32$' $DECO/FabOSrc && grep -q '^PaddingBottom=32$' $DECO/FabOSrc && grep -q '^PaddingTop=32$' $DECOL/FabOSLightrc && grep -q '^BorderLeft=0$' $DECO/FabOSrc && grep -q '^BorderRight=0$' $DECO/FabOSrc && grep -q '^BorderBottom=0$' $DECO/FabOSrc && grep -q 'A14 14 0 0 1 46 32' $DECO/decoration.svg && grep -q 'A14 14 0 0 1 68 46' $DECO/decoration.svg && test -L $DECOL/decoration.svg && grep -q '^P, R, TH = 32, 14, 36' $SRC/brand/gen/aurorae_theme.py && grep -q 'fill-opacity:0.004' $SRC/brand/gen/aurorae_theme.py && grep -q '^P, R, W, H = 32, 14, 400, 300' $SRC/tests/decoration-render-harness/probe.py"
chk "one shadow: corners-vm.sh wraps every ssh/scp in timeout and uses corners-sample.py (diagonal 12 px, along-edge ramp, edges 2..6, shadow present); its self-test passes" "grep -q 'vm() { timeout \"\$SSH_TIMEOUT\" \$SSH' $SRC/tests/corners-vm.sh && grep -q 'scp_from() { timeout' $SRC/tests/corners-vm.sh && ! grep -q '^vm() { \$SSH' $SRC/tests/corners-vm.sh && grep -q corners-sample.py $SRC/tests/corners-vm.sh && grep -q 'range(1, 13)' $SRC/tests/corners-sample.py && grep -q 'before the curve' $SRC/tests/corners-sample.py && python3 $SRC/tests/corners-sample.py --selftest | grep -q '^SELFTEST PASS'"
chk "one shadow: render test covers Fab Dark + Fab Light and probes every padding/notch pixel for the uniform carrier; design system + ADR-0019 amendment record the shader facts" "grep -q 'for scheme in dark light' $SRC/tests/decoration-render-test.sh && grep -q 'padding ring: uniform carrier only' $SRC/tests/decoration-render-harness/probe.py && grep -q 'notches: carrier, not a hole' $SRC/tests/decoration-render-harness/probe.py && grep -q 'UseNativeDecorationShadows=false' $SRC/docs/design/DESIGN_SYSTEM.md && grep -q 'Amendment (2026-09-16)' $SRC/docs/decisions/ADR-0019-rounded-corners-effect.md && grep -q 'tex.a == 0.0' $SRC/docs/decisions/ADR-0019-rounded-corners-effect.md"
# Second pass (2026-09-16, review): the shadow chain is observed in a REAL composited KWin inside the image (kwin_wayland --virtual on the
# host render node, OpenGL, the effect loaded), ShadowSize 45 -> 40 so that 8 px out on every corner diagonal is the background again.
chk "one shadow: live KWin gate — tests/corners-live-test.sh runs kwin_wayland --virtual in the image under timeout, has a --control (carrier off -> no shadow), spectacle unlocked by the plugin's test knob; harness files present" "grep -q 'timeout 240 podman run --rm --device' $SRC/tests/corners-live-test.sh && grep -q -- '--control' $SRC/tests/corners-live-test.sh && grep -q 'CARRIER_OFF' $SRC/tests/corners-live-test.sh && grep -q 'kwin_wayland --virtual' $SRC/tests/corners-live-harness/session.sh && grep -q 'KWIN_SCREENSHOT_NO_PERMISSION_CHECKS=1' $SRC/tests/corners-live-harness/session.sh && grep -q 'UseNativeDecorationShadows=' $SRC/tests/corners-live-harness/inner.sh && test -f $SRC/tests/corners-live-harness/windows.py && test -f $SRC/tests/corners-live-harness/geo.py && test -f $SRC/tests/corners-live-harness/crops.py && grep -q corners-sample.py $SRC/tests/corners-live-test.sh"
chk "one shadow: corners-sample.py enforces the brief's 8 px rule (BG_FROM=8: background from k=8 on every corner diagonal, noise floor 10) and models the shipped Size 40; corners-vm.sh + live test share it" "grep -q '^STEP_MAX, RISE_MAX, BG_MAX, BG_FROM, DIAG_SLACK, PRESENT_MIN = 12, 6, 10, 8, 8, 6$' $SRC/tests/corners-sample.py && grep -q 'tail = d\[BG_FROM - 1:\]' $SRC/tests/corners-sample.py && grep -q 'size_a = 40.0' $SRC/tests/corners-sample.py && grep -q 'background from k=' $SRC/tests/corners-sample.py && grep -q 'from 8 px on' $SRC/tests/corners-vm.sh && ! grep -q 'ShadowSize=45$' $KWRC"
chk "one shadow: the live-KWin numbers are on record — QA.md, ADR-0019 amendment (second pass), design system, generator docstring name tests/corners-live-test.sh" "grep -q 'corners-live-test.sh' $SRC/docs/QA.md && grep -q 'corners-live-test.sh' $SRC/docs/decisions/ADR-0019-rounded-corners-effect.md && grep -q 'Second pass (2026-09-16' $SRC/docs/decisions/ADR-0019-rounded-corners-effect.md && grep -q 'corners-live-test.sh' $SRC/docs/design/DESIGN_SYSTEM.md && grep -q 'corners-live-test.sh' $SRC/brand/gen/aurorae_theme.py"
exit $fail
