# Artwork, fonts, animation and 3D assets

All Fab OS artwork **shipped on the image** (logo, boot animation, greeter,
splash, wallpapers, icon tiles, 3D mesh) is **original work generated by the
scripts in `brand/gen/`** from the Fab OS mark (a ring with three woven
bars). Nothing is traced from, derived from, or resembles Canonical, KDE,
Apple, Microsoft or any other party's artwork. Files in this repository that
are *not* produced by `brand/gen/` are listed at the end of this document.

- Logo (`brand/logo/*.svg`), animated logo, Plymouth boot animation frames,
  SDDM background, wallpapers, KSplash artwork, icons, and the 3D logo mesh
  (`fabos-mark.glb`, `fabos-mark.obj`): copyright 2026 Patience AI, released
  under **Apache-2.0 OR CC0-1.0** at your option. You may use them without
  attribution, but see `TRADEMARKS.md` about using them to identify a product.
- Wallpapers are procedurally generated (gradient fields plus a subtle weave
  texture) and contain no photographs or third-party imagery.
- Typeface: **Inter** by The Inter Project Authors (SIL Open Font License 1.1)
  is the UI and branding face, shipped via the Ubuntu package `fonts-inter`.
  **JetBrains Mono** (SIL OFL 1.1) is the monospace face via
  `fonts-jetbrains-mono`. Neither font is embedded or modified in this repo.
- Icons not covered by the FabOS icon theme come from the KDE Breeze theme
  (LGPL-3.0), unmodified; the FabOS icon theme itself is described below.

Reproducibility: run `python3 brand/gen/make_assets.py --out brand/out` with
`fonts-inter` installed; outputs are deterministic (no randomness).

## Third-party icon glyphs (added 2026-09-11)

The Fab OS icon theme (`/usr/share/icons/FabOS`) draws the glyphs for the visible applications from **Google Material Symbols**
(github.com/google/material-design-icons), licensed **Apache-2.0**, placed on Fab OS-coloured tiles generated by `brand/gen/make_assets.py`.
All other icons come from KDE Breeze (LGPL-3.0) through theme inheritance. Firefox is installed from Mozilla's repository and keeps its own
branding and icon inside the application; the launcher tile uses a generic globe glyph, not the Firefox logo (Mozilla trademark).

## Files not generated by `brand/gen/` (added 2026-09-13)

- `marketing/fab-os-social-post*.png`: four promotional renders (a glossy sphere with a leaf-like glyph,
  "Fab OS" wordmark, the website address). They are **not** built from the Fab OS mark by `brand/gen/`, are not
  shipped on any image, and carry the caption "All rights reserved" inside the image. Their provenance
  (tool or author) and licence are **not recorded**; record them here and decide whether they fall under the
  repository's Apache-2.0 / CC0 grant or stay all-rights-reserved before the repository is made public.
- `packages/fabos-desktop/usr/share/plasma/look-and-feel/*/contents/previews/*.{png,jpg}`: screenshots of
  the Fab OS desktop taken in the test VM. They show Fab OS's own theme, wallpaper and icon tiles (Material
  Symbols glyphs, Apache-2.0) and are Apache-2.0 / CC0 like the rest of the artwork.
- `website/fabos.svg`: the Fab OS mark, hand-maintained copy of `brand/logo/`.
