units:
  enable:
    - name: NetworkManager
      mandatory: true
    - name: sddm
      mandatory: true
    - name: fabos-firstboot
      mandatory: false
    - name: fabos-feedback.socket
      mandatory: false
  disable:
    - name: casper
      mandatory: false
