defaultGroups:
  - name: users
  - name: sudo
    must_exist: true
  - name: adm
  - name: video
  - name: audio
  - name: plugdev
  - name: netdev
  - name: render
  - name: lpadmin
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
passwordRequirements:
  minLength: 6
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
  shell: /bin/bash
  forbidden_names: [ root, fabos ]
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "fabos-${first}"
  forbidden_names: [ localhost ]
