showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
  requiredStorage: 15
  requiredRam: 4
  internetCheckUrl: http://fabricos.patienceai.in/apt/
  check: [ storage, ram, power, internet, root ]
  required: [ storage, ram, root ]
