[Theme]
Current=fabos
CursorTheme=breeze_cursors
Font=@UI_FONT@,10

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
SessionDir=/usr/local/share/wayland-sessions
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1
